### PR TITLE
Rename ROUTING links to CORE.

### PR DESCRIPTION
**Pull request by ercanucan**
- Addresses https://github.com/netsec-ethz/scion-web/issues/58
- Renames ROUTING link types to CORE.
- Adapts tests and migrations accordingly.
- Fixed a unit test (caused by introduction of the Port field into the models via 940306c8b945081b86e83d8193475e404cf3c090).

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-web/68)

### CODE REVIEW

**Comment by ercanucan** [comment]
@kormat @klausman

**Comment by kormat** [comment]
One comment, otherwise LGTM.

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ad_manager/forms.py, line 100 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/68#-KehBXbOXVs2IOaT5hhp:-KehBXbOXVs2IOaT5hhq:bt6tpqu) ([raw file](https://github.com/netsec-ethz/scion-web/blob/57b2db8219db88fc9d018c7066c71736a52e63de/ad_manager/forms.py#L100)):*
> ```Python
> 
> class NewLinkForm(forms.Form):
>     link_types = ['PARENT', 'CHILD', 'PEER', 'CORE']
> ```

Rather than using string literals everywhere, why not use `lib.types.LinkType`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/68#-:-KehCMwOeOqZMEAq0V-Y:brhuj7e)*

**Comment by ercanucan** [comment]
@kormat Addressed your feedback wherever possible in the Python code and did a little bit more cleanup to a couple of other places which used string literals. Also further adapted test topology fixtures with recently added Port field for consistency.

---

Review status: 2 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[ad_manager/forms.py, line 100 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/68#-KehBXbOXVs2IOaT5hhp:-Ket0CanaRvWem-Wh6ic:bs7wumx) ([raw file](https://github.com/netsec-ethz/scion-web/blob/57b2db8219db88fc9d018c7066c71736a52e63de/ad_manager/forms.py#L100)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Rather than using string literals everywhere, why not use `lib.types.LinkType`?
</blockquote></details>

Done. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/68#-:-Ket0XsSVqNFGBsVqFyX:bxvhrwm)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/68#-:-KfAzs9bv0OJ0moVBktc:bnfp4nl)*

**Comment by ercanucan** [comment]
Thanks!

**Pull request merged**
