### PR TITLE
Go router config generation

### PR DESCRIPTION
**Pull request by ercanucan**
- Update supervisord config generation for services and
generate go router configuration.
- Small tidy up (variable names, white-space etc).
- Fix a broken API.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-web/54)

### CODE REVIEW

**Comment by ercanucan** [comment]
@kormat @klausman Separated this out into an independent PR for the sake of easier code reviewing. Includes Go router config generation and small updates to existing code. @FR4NK-W, in case you find time, a quick look on this PR would be appreciated :-)

**Comment by klausman** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ad_manager/views.py, line 866 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/54#-KdAEPBZqB16UDYhX9Sn:-KdAEPBZqB16UDYhX9So:b-i7ac1x) ([raw file](https://github.com/netsec-ethz/scion-web/blob/b552da863153a852e8798de19d27220c19aae795/ad_manager/views.py#L866)):*
> ```Python
>     ia = ISD_AS(isd_as)
>     isd_id = ia[0]
>     as_id = ia[1]
> ```

Unless you're using `ia` somewhere, this should beL
```
isd_id, as_id = ISD_AS(isd_as)
```

If you do use the `ia` object, it should have a better (longer) name.

---

*[ad_manager/views.py, line 914 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/54#-KdAEfxwppdu2I1H4b4P:-KdAEfxwppdu2I1H4b4Q:b-3m9f40) ([raw file](https://github.com/netsec-ethz/scion-web/blob/b552da863153a852e8798de19d27220c19aae795/ad_manager/views.py#L914)):*
> ```Python
>     zk_name_counter = 1
> 
>     for serv_type, type_key in types_keys:
> ```

Why did you shorten `service_type` into `serv_type`? If it's only to match `serv_name`, it would be better to expand that into `service_name`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/54)*

**Comment by ercanucan** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[ad_manager/views.py, line 866 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/54#-KdAEPBZqB16UDYhX9Sn:-KdBP5ub5MEfjek8Inh9:bkn5dc6) ([raw file](https://github.com/netsec-ethz/scion-web/blob/b552da863153a852e8798de19d27220c19aae795/ad_manager/views.py#L866)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Unless you're using `ia` somewhere, this should beL
```
isd_id, as_id = ISD_AS(isd_as)
```

If you do use the `ia` object, it should have a better (longer) name.
</blockquote></details>

Done. (It's not being used anywhere else)

---

*[ad_manager/views.py, line 914 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/54#-KdAEfxwppdu2I1H4b4P:-KdBRcYTfZjjkhAwH8JE:bywtzr1) ([raw file](https://github.com/netsec-ethz/scion-web/blob/b552da863153a852e8798de19d27220c19aae795/ad_manager/views.py#L914)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Why did you shorten `service_type` into `serv_type`? If it's only to match `serv_name`, it would be better to expand that into `service_name`
</blockquote></details>

Done. Yes, that was the intention. Changed `serv_name` to `service_name` instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/54)*

**Comment by klausman** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/54#-:-KdBVJwJ_-j86d19Mhi6:bnfp4nl)*

**Comment by kormat** [comment]
A couple of minor things, otherwise LGTM.

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[ad_manager/views.py, line 866 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/54#-KdAEPBZqB16UDYhX9Sn:-KdAst3i19ByZnt4UfXN:b-ok5ume) ([raw file](https://github.com/netsec-ethz/scion-web/blob/b552da863153a852e8798de19d27220c19aae795/ad_manager/views.py#L866)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Done. (It's not being used anywhere else)
</blockquote></details>

For future reference, `ia` is a strong convention in the python and go codebases:
```
$ git grep -E '(\<|_)ia\>' | wc -l
323
```

---

*[ad_manager/views.py, line 914 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/54#-KdAEfxwppdu2I1H4b4P:-KdR1pqx8DJZOs9_cAir:brnft3v) ([raw file](https://github.com/netsec-ethz/scion-web/blob/b552da863153a852e8798de19d27220c19aae795/ad_manager/views.py#L914)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Done. Yes, that was the intention. Changed `serv_name` to `service_name` instead.
</blockquote></details>

Wait, what does "service type" vs "service name" mean?

---

*[ad_manager/views.py, line 851 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-web/54#-KdR2MM2ECCJso9vDNXK:-KdR2MM2ECCJso9vDNXL:b-ecqvmk) ([raw file](https://github.com/netsec-ethz/scion-web/blob/39e6edb60b66a0466668f30d484466f9fe05826b/ad_manager/views.py#L851)):*
> ```Python
> 
> 
> def create_local_gen(isd_as, tp):
> ```

This function is 104 lines long. It's in dire need of refactoring (not for this PR, granted).

---

*[ad_manager/views.py, line 1017 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-web/54#-KdR21SwoxYSPRrkcoeq:-KdR21SwoxYSPRrkcoer:b-a467y6) ([raw file](https://github.com/netsec-ethz/scion-web/blob/39e6edb60b66a0466668f30d484466f9fe05826b/ad_manager/views.py#L1017)):*
> ```Python
>     :param str executable_name: the name of the executable.
>     :param str service_type: the type of the service (e.g. beacon_server).
>     :param str service_name: the name of the service (e.g. br1-8-1).
> ```

This isn't a service. It's a service instance.

---

*[ad_manager/views.py, line 1027 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-web/54#-KdR392in_j1JDqPlD5R:-KdR392in_j1JDqPlD5S:b-6u53an) ([raw file](https://github.com/netsec-ethz/scion-web/blob/39e6edb60b66a0466668f30d484466f9fe05826b/ad_manager/views.py#L1027)):*
> ```Python
>     if service_type == 'router':  # go router
>         env_tmpl += ',GODEBUG="cgocheck=0"'
>         cmd_tmpl = ('bash -c \'exec "bin/border" "-id" "%s" "-confd" ' +
> ```

`+` is unneeded. Same below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/54#-:-KdR4VQm3FVh8VpjN8Sj:bu3w0wt)*

**Comment by ercanucan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[ad_manager/views.py, line 914 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/54#-KdAEfxwppdu2I1H4b4P:-KdRb10xWoXAcdvb6Z3V:bq91fzj) ([raw file](https://github.com/netsec-ethz/scion-web/blob/b552da863153a852e8798de19d27220c19aae795/ad_manager/views.py#L914)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Wait, what does "service type" vs "service name" mean?
</blockquote></details>

`service_name` actually is `instance_name`. Updated.

---

*[ad_manager/views.py, line 851 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-web/54#-KdR2MM2ECCJso9vDNXK:-KdRa6n6JtG0P6EOwXSS:bwibnov) ([raw file](https://github.com/netsec-ethz/scion-web/blob/39e6edb60b66a0466668f30d484466f9fe05826b/ad_manager/views.py#L851)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This function is 104 lines long. It's in dire need of refactoring (not for this PR, granted).
</blockquote></details>

I agree, we have a couple of long functions like that in the legacy scion-web code. I am in the process re-writing part of this function as part of deploying the certs and TRCs coming through the scion-coord.

---

*[ad_manager/views.py, line 1017 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-web/54#-KdR21SwoxYSPRrkcoeq:-KdRbCm55sXt4ZhpK0xj:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/39e6edb60b66a0466668f30d484466f9fe05826b/ad_manager/views.py#L1017)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This isn't a service. It's a service instance.
</blockquote></details>

Done.

---

*[ad_manager/views.py, line 1027 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-web/54#-KdR392in_j1JDqPlD5R:-KdRbIB5b8VVhSr28TCN:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/39e6edb60b66a0466668f30d484466f9fe05826b/ad_manager/views.py#L1027)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`+` is unneeded. Same below.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/54)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/54#-:-KdV3N0QGnaw_nk_1stl:bnfp4nl)*

**Comment by ercanucan** [comment]
Thanks @kormat. Squashed the commits. If you can approve the PR, I will then merge it.

**Pull request merged**
