### PR TITLE
Changes needed for new SCION repo layout.

### PR DESCRIPTION
**Pull request by shitz**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-web/88)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[scripts/reload_data.py, line 29 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/88#-Km6gROKZtIvKwIWSiJ3:-Km6gROKZtIvKwIWSiJ4:bycdaf2) ([raw file](https://github.com/netsec-ethz/scion-web/blob/acbeaec921f50b9f9e1000ba30995b494854dfcf/scripts/reload_data.py#L29)):*
> ```Python
> SCION_ROOT_DIR = d(d(WEB_SCION_DIR))  # noqa
> SCION_PYTHON_ROOT_DIR = os.path.join(SCION_ROOT_DIR, 'python')
> sys.path.insert(0, WEB_SCION_DIR)
> ```

I would insert the web scion dir after the other two entries. That way if there's ever a namespace conflict, it will be more immediately obvious.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/88)*

**Comment by shitz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[scripts/reload_data.py, line 29 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/88#-Km6gROKZtIvKwIWSiJ3:-Km6hCdP_40LCHJjMcGX:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/acbeaec921f50b9f9e1000ba30995b494854dfcf/scripts/reload_data.py#L29)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I would insert the web scion dir after the other two entries. That way if there's ever a namespace conflict, it will be more immediately obvious.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/88)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/88#-:-Km6kkLBiMvbP_CrGpFg:bnfp4nl)*

**Comment by ercanucan** [comment]
+1

**Pull request merged**
