### PR TITLE
Generate -prom flag for supervisord configuration of border routers.

### PR DESCRIPTION
**Pull request by ercanucan**
- Fixes https://github.com/netsec-ethz/scion-web/issues/85
- Also changes the Python code line-length to 100 similar to the main SCION code-base.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-web/87)

### CODE REVIEW

**Comment by ercanucan** [comment]
@klausman @kormat

**Comment by klausman** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ad_manager/util/local_config_generator.py, line 165 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/87#-Klx2CIvemicQULxx0jX:-Klx2CIvemicQULxx0jY:b6ie587) ([raw file](https://github.com/netsec-ethz/scion-web/blob/dc157806e69224013bc80d466f6fba6c56f45c0e/ad_manager/util/local_config_generator.py#L165)):*
> ```Python
>         env_tmpl += ',GODEBUG="cgocheck=0"'
>         prom_addr = "%s:%s" % (instance_dict['Addr'], instance_dict['Port'] + PROM_BR_PORT_OFFSET)
>         cmd = ("bash -c 'exec bin/%s -id \"%s\" -confd \"%s\" -prom \"%s\" &>logs/%s.OUT'") % (
> ```

I recommend switching the outer quotes to `'` here and move the backslashes to the `'` around `exec ...`

Matter of taste, so feel free to ignore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/87#-:-Klx2_eyfhN4YtFx3Or9:bnfp4nl)*

**Comment by ercanucan** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[ad_manager/util/local_config_generator.py, line 165 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/87#-Klx2CIvemicQULxx0jX:-Km1RViPvWDc6YujsIG0:b2jotsr) ([raw file](https://github.com/netsec-ethz/scion-web/blob/dc157806e69224013bc80d466f6fba6c56f45c0e/ad_manager/util/local_config_generator.py#L165)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

I recommend switching the outer quotes to `'` here and move the backslashes to the `'` around `exec ...`

Matter of taste, so feel free to ignore.
</blockquote></details>

Done. In both places. I agree it looks more neat this way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/87)*

**Comment by klausman** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/87)*

**Comment by ercanucan** [comment]
Can this be merged now? @kormat would you also like to have a look?

**Pull request merged**
