### PR TITLE
Simple configuration with single public IP

### PR DESCRIPTION
**Pull request by ercanucan**
This PR includes the following:
- Introduces the Simple configuration with single public IP.
- Given the public IP of the host, the topology configuration is populated
automatically from a template file.
- Creates and sends a connection request automatically to the desired AS.
- Groups the requests tabs in the UI into two: Requests from My AS
vs. Requests from Other ASes.
- Small fixes and clean up of some unused code.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-web/74)

### CODE REVIEW

**Comment by ercanucan** [comment]
@FR4NK-W  @klausman or @kormat

**Comment by ercanucan** [comment]
@hausheer it would be great if you could have a look at this when you find some time.

**Comment by kormat** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ad_manager/util/simple_config/simple_config_topo.tmpl, line 44 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/74#-KgxkCOvVkB_b734iArw:-KgxkCOwYZD1v_H2FaWN:b4w4pb5) ([raw file](https://github.com/netsec-ethz/scion-web/blob/30f82148ec756e1d37417bc1d2dd80e555f673cb/ad_manager/util/simple_config/simple_config_topo.tmpl#L44)):*
> ```
> Zookeepers:
>   1:
>     Addr: ${IP}
> ```

Running zookeeper on a public IP is a Bad Idea. It has no authn/authz by default. We can't assume proper firewalling, etc. I suggest `127.0.0.1` instead.

Oh, but zookeeper will actually bind to the public IP anyway :/ This must be changed for the simple setup. Adding `clientPortAddress=127.0.0.1` to `/etc/zookeeper/conf/zoo.cfg` would fix it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/74)*

**Comment by FR4NK-W** [comment]
The format used for the PollEvents by scion-coord and web-scion does no longer match. web-scion now expects an ReceivedConnReplies, but receives a ConnReplies entry from scion-coord.
Error handling when the certificate does not match the expected value could be improved.

**Comment by kormat** [comment]
Is this PR stalled?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/74#-:-KjN-oWAKzA0O6lAIafv:b-6d7bkj)*

**Comment by ercanucan** [comment]
Yes, please hold-off reviewing this one until we get the https://github.com/netsec-ethz/scion-web/pull/75 in. I worked out your feedback for this based on the re-factored code (#75) and will update this as soon as that one is merged.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/74#-:-KjN9aQFf0PyF-8k6JBT:b-f1bg66)*

**Comment by ercanucan** [comment]
Review status: 6 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[ad_manager/util/simple_config/simple_config_topo.tmpl, line 44 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/74#-KgxkCOvVkB_b734iArw:-KkQeuyrR6fQqMYML3ze:b53t64r) ([raw file](https://github.com/netsec-ethz/scion-web/blob/30f82148ec756e1d37417bc1d2dd80e555f673cb/ad_manager/util/simple_config/simple_config_topo.tmpl#L44)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Running zookeeper on a public IP is a Bad Idea. It has no authn/authz by default. We can't assume proper firewalling, etc. I suggest `127.0.0.1` instead.

Oh, but zookeeper will actually bind to the public IP anyway :/ This must be changed for the simple setup. Adding `clientPortAddress=127.0.0.1` to `/etc/zookeeper/conf/zoo.cfg` would fix it.
</blockquote></details>

Done. We generate different ZK config files depending on whether we are operating in normal mode or simple mode. I added a `simple_conf`mode field to the AS database table in order to indicate that an AS is configured with a simple mode.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/74)*

**Comment by ercanucan** [comment]
@kormat: updated this PR based on your feedback. would be great when you get a chance to have a look at it. 
@fr4nk-w: could you be more specific about your comment on this PR saying "Error handling when the certificate does not match the expected value could be improved". We do not yet do verification of certificates in connection request. So far we have generation of new cert for a newly joining AS and sending certs across for connection requests. Do you mean a more general error handling if a certificate, trc or a key is not found in the DB?

---

Review status: 6 of 13 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/74#-:-KkQfbUMebna4aVUdVSe:b-ku22jh)*

**Comment by kormat** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ad_manager/util/local_config_generator.py, line 417 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-web/74#-KkoJZrIsYB6buk8zelB:-KkoJZrIsYB6buk8zelC:b-cx22pj) ([raw file](https://github.com/netsec-ethz/scion-web/blob/60dcfcadb13e3a4e587529f8aaa6d89617eb34c4/ad_manager/util/local_config_generator.py#L417)):*
> ```Python
>         'syncLimit': 5,
>         'dataDir': '/var/lib/zookeeper',
>         'dataLogDir': '/run/shm/host-zk',
> ```

For simple mode, i would unset this. The amount of traffic the zookeeper instance in simple mode has to deal with will be very small, and not using a tmpfs dir means one less thing to go wrong. (E.g. this dir doesn't exist on boot, so zookeeper will keep continuously restarting if configured to use it, until scion.sh finally creates it).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/74)*

**Comment by ercanucan** [comment]
Review status: 11 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[ad_manager/util/local_config_generator.py, line 417 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-web/74#-KkoJZrIsYB6buk8zelB:-KkpjylhRALCBOND0H9Z:bakri4y) ([raw file](https://github.com/netsec-ethz/scion-web/blob/60dcfcadb13e3a4e587529f8aaa6d89617eb34c4/ad_manager/util/local_config_generator.py#L417)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

For simple mode, i would unset this. The amount of traffic the zookeeper instance in simple mode has to deal with will be very small, and not using a tmpfs dir means one less thing to go wrong. (E.g. this dir doesn't exist on boot, so zookeeper will keep continuously restarting if configured to use it, until scion.sh finally creates it).
</blockquote></details>

Done. Yes, that makes sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/74)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/74#-:-KkuJ3p12GOevzwFux-3:bnfp4nl)*

**Pull request merged**
