### PR TITLE
Added a new feature "Save All Topology Files"

### PR DESCRIPTION
**Pull request by jonghoonkwon**
- New buttons in a Web root page and ISD pages
- "Save All" button in a Web root page generates configuration files for all ASes
- "Save All" button in a ISD page generates configuration files for ASes in the ISD

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-web/100)

### CODE REVIEW

**Comment by ercanucan** [comment]
Look good to me in general. Though one problem is that, as discussed, this approach does not update the ansible host files.

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[ad_manager/urls.py, line 61 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/100#-KoMAoFcBVZQAaerVx4E:-KoMAoFcBVZQAaerVx4F:b-nnjj3h) ([raw file](https://github.com/netsec-ethz/scion-web/blob/d4d9339234834ed8935b97a01083347ffc076549/ad_manager/urls.py#L61)):*
> ```Python
>     url(r'^isds/poll_join_reply/?$',
>         views.poll_join_reply, name='poll_join_reply'),
>     url(r'^isds/save_topology/?$',
> ```

We can rename this to `save_all_topologies` or something along those lines.

---

*[ad_manager/views.py, line 250 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/100#-KoMBE7J9lvMxif96ZB9:-KoMBE7J9lvMxif96ZBA:b-ejfp4n) ([raw file](https://github.com/netsec-ethz/scion-web/blob/d4d9339234834ed8935b97a01083347ffc076549/ad_manager/views.py#L250)):*
> ```Python
>         all_ases = AD.objects.all()
>         for ad_obj in all_ases:
>             isd_as = '%s-%s' % (ad_obj.isd_id, ad_obj.as_id)
> ```

Better to use the built-in `ISD_AS` call here.

---

*[ad_manager/templates/ad_manager/isd_detail.html, line 57 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/100#-KoMBP8Uts67c_gtWBH8:-KoMBP8Uts67c_gtWBH9:b-qjgrw1) ([raw file](https://github.com/netsec-ethz/scion-web/blob/d4d9339234834ed8935b97a01083347ffc076549/ad_manager/templates/ad_manager/isd_detail.html#L57)):*
> ```HTML
>         {% csrf_token %}
>         {% for ad in object_list %}
>           <input type="hidden" name="ISD_AS" value="{{ad.isd.id}}-{{ad.as_id}}">
> ```

I am not sure we need to full `ISD_AS` here. Just `ISD`would be sufficient

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/100#-:-KoMFP9Xv7f1V8DzLnHr:b-lx6lvk)*

**Comment by jonghoonkwon** [comment]
Now, the modified version would be update the ansible host files too.

---

Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[ad_manager/urls.py, line 61 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/100#-KoMAoFcBVZQAaerVx4E:-KoNg7jziFVoC0flOyOa:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/d4d9339234834ed8935b97a01083347ffc076549/ad_manager/urls.py#L61)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

We can rename this to `save_all_topologies` or something along those lines.
</blockquote></details>

Done.

---

*[ad_manager/views.py, line 250 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/100#-KoMBE7J9lvMxif96ZB9:-KoNg6MDsVT122fLkEiK:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/d4d9339234834ed8935b97a01083347ffc076549/ad_manager/views.py#L250)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Better to use the built-in `ISD_AS` call here.
</blockquote></details>

Done.

---

*[ad_manager/templates/ad_manager/isd_detail.html, line 57 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/100#-KoMBP8Uts67c_gtWBH8:-KoNg71fmbWmxsQAxFi-:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/d4d9339234834ed8935b97a01083347ffc076549/ad_manager/templates/ad_manager/isd_detail.html#L57)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

I am not sure we need to full `ISD_AS` here. Just `ISD`would be sufficient
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/100#-:-KoNg8eIm4TCFyOv_IcT:byu7h0)*

**Comment by jonghoonkwon** [comment]
@ercanucan, 
Could you resolve the discussions over this PR.
If you don't mine, I'm gonna merge it to the master.

**Comment by ercanucan** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/100#-:-L-MibCaowBCJ7sWUU7Z:bnfp4nl)*

**Comment by ercanucan** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/100)*

**Comment by ercanucan** [comment]
@jonghoonkwon Done.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/100#-:-L-MieAiY_98XxFBUAy8:bcjcywm)*

**Pull request merged**
