### PR TITLE
Adaptation of the simple config mode to the new topo format.

### PR DESCRIPTION
**Pull request by ercanucan**
NOTE: This PR depends on https://github.com/netsec-ethz/scion-web/pull/91
Therefore can only be merged once #91 is in.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-web/92)

### CODE REVIEW

**Comment by ercanucan** [comment]
@jonghoonkwon Adaptation of the simple config mode should be along these lines. Please have a look.

**Comment by ercanucan** [comment]
@jonghoonkwon it would be great if you could take a look at this

**Comment by jonghoonkwon** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/92#-:-KoNkbl2Ku50pGZiSgCY:bnfp4nl)*

**Comment by jonghoonkwon** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/92)*

**Pull request merged**
