### PR TITLE
Added generation of prometheus endpoints to scion-web

### PR DESCRIPTION
**Pull request by shitz**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-web/95)

### CODE REVIEW

**Comment by ercanucan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[ad_manager/util/local_config_generator.py, line 339 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/95#-KoBidciXVE23VDRqs6K:-KoBidcja4DkAU3ocJOf:b1lm9wm) ([raw file](https://github.com/netsec-ethz/scion-web/blob/a9fd1202b794939eee1d5a03fb95998d35361d00/ad_manager/util/local_config_generator.py#L339)):*
> ```Python
>     :param str as_path: The path of the given AS.
>     """
>     ele_dict = defaultdict(list)
> ```

I think it may be better to name this `elem_dict`. The rest of the code uses `elem` as short for scion elements.

---

*[ad_manager/util/local_config_generator.py, line 340 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/95#-KoBirrxj1iOIji1DwNK:-KoBirrymFo36CP3wyAT:bge79tt) ([raw file](https://github.com/netsec-ethz/scion-web/blob/a9fd1202b794939eee1d5a03fb95998d35361d00/ad_manager/util/local_config_generator.py#L340)):*
> ```Python
>     """
>     ele_dict = defaultdict(list)
>     for br_id, br_ele in tp['BorderRouters'].items():
> ```

similarly, `br_elem` might be a better name.

---

*[ad_manager/util/local_config_generator.py, line 353 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/95#-KoBjMGY2cgRr7BfiVgN:-KoBjMGY2cgRr7BfiVgO:bxffxnx) ([raw file](https://github.com/netsec-ethz/scion-web/blob/a9fd1202b794939eee1d5a03fb95998d35361d00/ad_manager/util/local_config_generator.py#L353)):*
> ```Python
> 
> 
> def _write_prometheus_config_files(local_gen_path, as_path, ele_dict):
> ```

It wold be nice if you can add a comment here about what the function does. The rest of the file has comments for each function and it would nice to keep doing it this way for all the future code.

---

*[ad_manager/util/local_config_generator.py, line 362 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/95#-KoBk0AbgGZW2zDXP2cH:-KoBk0AbgGZW2zDXP2cI:b-ahkv8k) ([raw file](https://github.com/netsec-ethz/scion-web/blob/a9fd1202b794939eee1d5a03fb95998d35361d00/ad_manager/util/local_config_generator.py#L362)):*
> ```Python
>     _write_prometheus_config_file(as_path, job_dict)
>     # Regenerate the top-level prometheus config file.
>     # XXX: This shouldn't be here.
> ```

Instead of this comment, maybe say something like "TODO: generation of the top level prom config should be done elsewhere". Also it would be nice to add your github ID.

---

*[ad_manager/util/local_config_generator.py, line 416 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/95#-KoBlRbDV2xD9eYrq8dk:-KoBlRbElAtDuMFj50ft:b-j1rkxl) ([raw file](https://github.com/netsec-ethz/scion-web/blob/a9fd1202b794939eee1d5a03fb95998d35361d00/ad_manager/util/local_config_generator.py#L416)):*
> ```Python
>         ia = ISD_AS.from_values(as_obj.isd_id, as_obj.as_id)
>         for ele_type, target_file in PrometheusGenerator.TARGET_FILES.items():
>             targets_path = os.path.join(
> ```

could this not fit in 2 lines instead of 3?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/95)*

**Comment by shitz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[ad_manager/util/local_config_generator.py, line 339 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/95#-KoBidciXVE23VDRqs6K:-KoBmscExWbZIBRvf3y-:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/a9fd1202b794939eee1d5a03fb95998d35361d00/ad_manager/util/local_config_generator.py#L339)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

I think it may be better to name this `elem_dict`. The rest of the code uses `elem` as short for scion elements.
</blockquote></details>

Done.

---

*[ad_manager/util/local_config_generator.py, line 340 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/95#-KoBirrxj1iOIji1DwNK:-KoBmwqayAE2U592niq6:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/a9fd1202b794939eee1d5a03fb95998d35361d00/ad_manager/util/local_config_generator.py#L340)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

similarly, `br_elem` might be a better name.
</blockquote></details>

Done.

---

*[ad_manager/util/local_config_generator.py, line 353 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/95#-KoBjMGY2cgRr7BfiVgN:-KoBnXB3b123h_qsYsS8:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/a9fd1202b794939eee1d5a03fb95998d35361d00/ad_manager/util/local_config_generator.py#L353)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

It wold be nice if you can add a comment here about what the function does. The rest of the file has comments for each function and it would nice to keep doing it this way for all the future code.
</blockquote></details>

Done.

---

*[ad_manager/util/local_config_generator.py, line 362 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/95#-KoBk0AbgGZW2zDXP2cH:-KoBnxkvAiAdn2LUEBgN:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/a9fd1202b794939eee1d5a03fb95998d35361d00/ad_manager/util/local_config_generator.py#L362)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Instead of this comment, maybe say something like "TODO: generation of the top level prom config should be done elsewhere". Also it would be nice to add your github ID.
</blockquote></details>

Done.

---

*[ad_manager/util/local_config_generator.py, line 416 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/95#-KoBlRbDV2xD9eYrq8dk:-KoBo2FvNrxJQEFxyA-i:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/a9fd1202b794939eee1d5a03fb95998d35361d00/ad_manager/util/local_config_generator.py#L416)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

could this not fit in 2 lines instead of 3?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/95)*

**Comment by ercanucan** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/95#-:-KoCbb2jfVP6JQgXuEWS:bnfp4nl)*

**Comment by ercanucan** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/95)*

**Comment by ercanucan** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/95)*

**Pull request merged**
