### PR TITLE
Adapt to refactoring of lib/util.py

### PR DESCRIPTION
**Pull request by Oncilla**
According to PR https://github.com/netsec-ethz/scion/pull/1108

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-web/86)

### CODE REVIEW

**Comment by ercanucan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[ad_manager/util/local_config_generator.py, line 28 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/86#-KlNKZrpREWzqEI2YpX_:-KlNKZrqYvpFVlYIVcsA:b-dcz01w) ([raw file](https://github.com/netsec-ethz/scion-web/blob/80d6652757aee3942a0ed451f26dedfa9b966d69/ad_manager/util/local_config_generator.py#L28)):*
> ```Python
> 
> # SCION
> from lib.crypto.asymcrypto import get_enc_key_file_path, get_sig_key_file_path
> ```

It would be better if you could do the multiple imports this way:
```
from lib.crypto.asymcrypto import (
    get_enc_key_file_path,
    get_sig_key_file_path,
)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/86)*

**Comment by Oncilla** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[ad_manager/util/local_config_generator.py, line 28 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/86#-KlNKZrpREWzqEI2YpX_:-KlNbbUIURSGnQtc-1pB:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/80d6652757aee3942a0ed451f26dedfa9b966d69/ad_manager/util/local_config_generator.py#L28)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

It would be better if you could do the multiple imports this way:
```
from lib.crypto.asymcrypto import (
    get_enc_key_file_path,
    get_sig_key_file_path,
)
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/86)*

**Comment by ercanucan** [comment]
@oncilla Just one more thing: We now need to provide a SigningKey object for Certificate creation inside views.py, at line 292.  Such as `SigningKey(signing_as_sig_priv_key)`.  And the import line should go to External packages section as you did with the main code-base.

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/86#-:-KlOX02gCaMjFq4DfcUG:b-6ug7az)*

**Comment by Oncilla** [comment]
Right. Could you quickly check if everything is working fine?

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/86#-:-KlObHuEreAOts0j6eLq:b-wb1avb)*

**Comment by ercanucan** [comment]
:lgtm: yes, the cert generation works as expected.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/86#-:-KlOgN-z1RzKMW3XBX8v:b-d6j04z)*

**Comment by ercanucan** [comment]
Please squash the commits and we can merge.

**Comment by Oncilla** [comment]
Can you update the reference in the main-repo, please.

**Comment by ercanucan** [comment]
ok, will do

**Pull request merged**
