### PR TITLE
Small refactoring of local config gen libs

### PR DESCRIPTION
**Pull request by ercanucan**
Minor refactoring of the local config generator and local config util libraries,
in order to be used by scion-coord, for packaging endhost and sciond configuration
into SCIONLab VMs.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-web/113)

### CODE REVIEW

**Comment by ercanucan** [comment]
@jonghoonkwon @mlegner Would be great if you can have a look at this as soon as you have a chance.

**Comment by mlegner** [comment]
:lgtm: And works fine together with https://github.com/netsec-ethz/scion-coord/pull/101.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/113#-:-Ky27P6POJV2SVN-v5Vu:b-jc9lgk)*

**Comment by ercanucan** [comment]
Thanks, please resolve the discussions on Reviwable so that we can merge.

**Comment by jonghoonkwon** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/113#-:-KyAwNJO4hX-m6KVJsNk:bnfp4nl)*

**Comment by ercanucan** [comment]
Thanks!

**Pull request merged**
