### PR TITLE
Extend UI to provide public and bind addresses for BRs

### LINKED ISSUE #107: Extend UI to provide public and bind addresses for BRs
scion-web UI needs to be slightlly extended to provide public and bind addresses for BRs, as we are moving to a topology where we run whole ASes on AWS.

### PR DESCRIPTION
**Pull request by jonghoonkwon**
Fixes #107

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-web/111)

### CODE REVIEW

**Comment by ercanucan** [comment]
:lgtm: (only a couple of minor things)

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[ad_manager/views.py, line 635 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/111#-KxEBUbr5Jbf3PC1bN_0:-KxEBUbr5Jbf3PC1bN_1:b51jqsz) ([raw file](https://github.com/netsec-ethz/scion-web/blob/75619d226f89a94e29efffb23b6254efbed00f84/ad_manager/views.py#L635)):*
> ```Python
>         context['received_requests'] = resp['ConnRequests']
>         context['received_conn_replies'] = resp['ConnReplies']
> ```

unnecessary white-space

---

*[ad_manager/templates/ad_manager/partials/topology_input.html, line 202 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/111#-KxEAdUEDBfG0v0cTkpx:-KxEAdUEDBfG0v0cTkpy:b6izfky) ([raw file](https://github.com/netsec-ethz/scion-web/blob/cd7c23a994d8a16be79c5c5e2ca8216d81754f88/ad_manager/templates/ad_manager/partials/topology_input.html#L202)):*
> ```HTML
>                       </div>
>                     </div>
>                     <br/>
> ```

seems like we lost this break  in the process of indentation adjustments?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/111#-:-KxEBiHHUYx93n9mN3R0:b-gzze5m)*

**Comment by ercanucan** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[ad_manager/templates/ad_manager/partials/topology_input.html, line 163 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/111#-KxHnP0raGlwF6hmjvqK:-KxHnP0s7ZZ97Ud1RXQ5:b-2x9gj) ([raw file](https://github.com/netsec-ethz/scion-web/blob/75619d226f89a94e29efffb23b6254efbed00f84/ad_manager/templates/ad_manager/partials/topology_input.html#L163)):*
> ```HTML
> 
>             <div class="form-group">
>               <label class="control-label col-sm-2" for="inputInterfaceRemoteAddress">Remote address the link</label> 
> ```

please also check this line. seems like an additional whitespace

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/111)*

**Comment by jonghoonkwon** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[ad_manager/views.py, line 635 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/111#-KxEBUbr5Jbf3PC1bN_0:-KxHQahzSUjYmtk7W2UT:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/75619d226f89a94e29efffb23b6254efbed00f84/ad_manager/views.py#L635)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

unnecessary white-space
</blockquote></details>

Done.

---

*[ad_manager/templates/ad_manager/partials/topology_input.html, line 163 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/111#-KxHnP0raGlwF6hmjvqK:-KxHouf-Xzk7H92FdXQB:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/75619d226f89a94e29efffb23b6254efbed00f84/ad_manager/templates/ad_manager/partials/topology_input.html#L163)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

please also check this line. seems like an additional whitespace
</blockquote></details>

Done.

---

*[ad_manager/templates/ad_manager/partials/topology_input.html, line 202 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/111#-KxEAdUEDBfG0v0cTkpx:-KxHovqPHuaxcIHki4Zf:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/cd7c23a994d8a16be79c5c5e2ca8216d81754f88/ad_manager/templates/ad_manager/partials/topology_input.html#L202)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

seems like we lost this break  in the process of indentation adjustments?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/111)*

**Comment by ercanucan** [comment]
:lgtm: (please squash the commits)

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/111#-:-KxIEM_jWmfHfrwNRXXg:boe4lvk)*

**Comment by ercanucan** [comment]
Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/111)*

**Pull request merged**
