### PR TITLE
Initial work on switching to new topology format

### PR DESCRIPTION
**Pull request by ercanucan**
Continuation of @jonghoonkwon's PR https://github.com/netsec-ethz/scion-web/pull/91

 - Adds new database tables to support the new topology format
 - Generates topology both in the older yaml format and the new json format.
 - Includes necessary updates to front-end in order to support existing functionalities.
 - Updates and adapts unit test and test fixtures.
 - Currently uses one Public and one Bind address per services and routers.
 - Currently assumes IPv4 for the address types and UDP/IPv4 for the overlay type.
 - Does not yet remove the existing schemas.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-web/93)

### CODE REVIEW

**Comment by ercanucan** [comment]
@shitz An initial feedback on this PR would be great when you get a chance.

**Comment by shitz** [comment]
Reviewed 12 of 18 files at r1.
Review status: 11 of 18 files reviewed at latest revision, 16 unresolved discussions.

---

*[ad_manager/forms.py, line 80 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-Knik_zz4z6sQlXdshxZ:-Knik_zz4z6sQlXdshx_:b4twazd) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/forms.py#L80)):*
> ```Python
>         # populate the choice field with options to choose from
>         for router in ad.borderrouter_set.all():
>             for router_addr in router.borderrouteraddress_set.all():
> ```

Can you rename these parameters to `border_router`, `border_router_address` etc. Much easier to read this way.

---

*[ad_manager/models.py, line 38 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-Knikp13wbhpS5Gw9c9g:-Knikp14PodQAUz6I0G7:b-ckb5ov) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/models.py#L38)):*
> ```Python
> from ad_manager.util.common import empty_dict
> from ad_manager.util.defines import (
>     SERVICE_ADDR_TYPES,
> ```

sort imports

---

*[ad_manager/models.py, line 122 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-Knim0BhEeQwGuL1bh7G:-Knim0BhEeQwGuL1bh7H:b-rkgd9z) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/models.py#L122)):*
> ```Python
>             out_dict['BorderRouters'][str(router.name)] = router.get_dict()
>         for service in self.service_set.all():
>             if 'bs' in service.name:
> ```

`service.name.startswith('bs')` would be more understandable

---

*[ad_manager/models.py, line 123 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-KnimL-x-MUFLwQO40mM:-KnimL-x-MUFLwQO40mN:bvh8he3) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/models.py#L123)):*
> ```Python
>         for service in self.service_set.all():
>             if 'bs' in service.name:
>                 out_dict['BeaconService'][str(service.name)] = service.get_dict()
> ```

I think there is no need for `str()` around `service.name`

---

*[ad_manager/models.py, line 133 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-KnimjoXgoWs4lZWoKOy:-KnimjoXgoWs4lZWoKOz:b8583eg) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/models.py#L133)):*
> ```Python
> 
>     def get_all_elements(self):
>         elements = [self.borderrouter_set.all(), self.service_set.all()]
> ```

`element_groups` would be a more fitting name

---

*[ad_manager/models.py, line 152 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-KninSfCMV8jUIaRKnrJ:-KninSfCMV8jUIaRKnrK:bxb9wvj) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/models.py#L152)):*
> ```Python
>             br_obj, _ = BorderRouter.objects.update_or_create(name=name, ad=self)
>             br_addr_idx = []
>             for int_addr_idx in range(len(router['InternalAddrs'])):
> ```

`for int_addr_idx, router_addr in router['InternalAddrs']:`

---

*[ad_manager/models.py, line 153 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-KninuQNgIaZCfVCMlFy:-KninuQNgIaZCfVCMlFz:b-gjkkr3) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/models.py#L153)):*
> ```Python
>             br_addr_idx = []
>             for int_addr_idx in range(len(router['InternalAddrs'])):
>                 for attr in SERVICE_ADDR_TYPES:
> ```

How about `for addr_attr in ADDR_ATTRIBUTES`? `SERVICE_ADDR_TYPES` seems to contain `Public` and `Bind` and for me the name was very misleading.

---

*[ad_manager/models.py, line 154 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-KninqATzg3R9RlbrlAM:-KninqATzg3R9RlbrlAN:b-efx5i3) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/models.py#L154)):*
> ```Python
>             for int_addr_idx in range(len(router['InternalAddrs'])):
>                 for attr in SERVICE_ADDR_TYPES:
>                     router_addr = router['InternalAddrs'][int_addr_idx]
> ```

no need for this anymore if you apply my change above

---

*[ad_manager/models.py, line 193 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-KnipMpByalTqZYqWw5c:-KnipMpByalTqZYqWw5d:bn0aad6) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/models.py#L193)):*
> ```Python
>                 if 'Bind' in intf.keys():
>                     br_inft_obj.update(
>                         bind_addr=intf['Public']['Addr'],
> ```

Shouldn't this be `bind_addr=intf['Bind']['Addr']`?

---

*[ad_manager/models.py, line 205 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-KnipX1aKBwWssfoUil5:-KnipX1b9LiW-fSVBMwO:b-33b6k6) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/models.py#L205)):*
> ```Python
>         for name, service in service_dict.items():
>             srv_obj, _ = Service.objects.update_or_create(name=name, ad=self)
>             for attr in SERVICE_ADDR_TYPES:
> ```

See comment above

---

*[ad_manager/models.py, line 208 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-Knipo8gzuu3nKeJxtp-:-Knipo8hdddD7bgXcRX-:b-7q50vu) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/models.py#L208)):*
> ```Python
>                 if attr not in service.keys():
>                     continue
>                 for addr_idx in range(len(service[attr])):
> ```

`for addr_idx, addr_info in enumerate(service[attr])):`

---

*[ad_manager/models.py, line 282 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-KniqQrI4rW4Ij6L78Dg:-KniqQrI4rW4Ij6L78Dh:b-5ho3qj) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/models.py#L282)):*
> ```Python
>     ad = models.ForeignKey(AD)
> 
>     class Meta:
> ```

Is this somehow needed by the framework? Otherwise you can define an abstract class like this:
```
import abc

class AddressElement(models.Model, metaclass=abc.ABCMeta)
```

---

*[ad_manager/models.py, line 292 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-KnirVjMs9jUaiVlNhAC:-KnirVjMs9jUaiVlNhAD:b-mg6pc7) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/models.py#L292)):*
> ```Python
>     def get_dict(self):
>         # TODO(jonghoonkwon): Fix this method to return a service dict
>         out_dict = super(Service, self).get_dict()
> ```

What does this do exactly? Right now it could be avoided I think, since a super class will already implement it and you don't do anything here. Same for other `get_dict` methods

---

*[ad_manager/views.py, line 602 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-KnisNa7Z9-jafqpyNXL:-KnisNa7Z9-jafqpyNXM:bjfinmg) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/views.py#L602)):*
> ```Python
>         # Sort by address numerically
>         lists_to_sort = ['service_addrs', 'router_addrs', 'interface_addrs']
>         for list_name in lists_to_sort:
> ```

No need to define `lists_to_sort`

---

*[ad_manager/views.py, line 1013 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-KnitxGRbioGR4fp_qwq:-KnitxGRbioGR4fp_qwr:b-4dx2sw) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/views.py#L1013)):*
> ```Python
>     # IP:port uniqueness in AS check
>     all_ip_port_pairs = []
>     for r in service_types:
> ```

```
for svc_type in service_types:
    for entry in topo_dict[svc_type]:
        for addr_info in entry['Public']:
            curr_pair = "%s:%s" % (addr_info['Addr'], addr_info['L4Port'])
```

---

*[ad_manager/views.py, line 1020 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-Kniv7-vOCej4mdwPPv_:-Kniv7-vOCej4mdwPPva:byr4ffv) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/views.py#L1020)):*
> ```Python
>                     servers_of_type_r[server]['Public'][i]['L4Port'])
>             all_ip_port_pairs.append(curr_pair)
>     for server in topo_dict['ZookeeperService']:
> ```

see above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93)*

**Comment by ercanucan** [comment]
Review status: 10 of 18 files reviewed at latest revision, 16 unresolved discussions.

---

*[ad_manager/forms.py, line 80 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-Knik_zz4z6sQlXdshxZ:-Kno4Muf65yahZjPnWBc:b-6fnjmn) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/forms.py#L80)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Can you rename these parameters to `border_router`, `border_router_address` etc. Much easier to read this way.
</blockquote></details>

as discussed, that's a Django feature for reverse lookup of foreign keys. there seems to be a way to rename them, but it requires a little bit effort. if that bothers you, I can do it in a follow-up PR.

---

*[ad_manager/models.py, line 38 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-Knikp13wbhpS5Gw9c9g:-Knn6gzZd2vkQe8Mrj5f:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/models.py#L38)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

sort imports
</blockquote></details>

Done.

---

*[ad_manager/models.py, line 122 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-Knim0BhEeQwGuL1bh7G:-Knn7m8eylGjG3aU19hK:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/models.py#L122)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

`service.name.startswith('bs')` would be more understandable
</blockquote></details>

Done.

---

*[ad_manager/models.py, line 123 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-KnimL-x-MUFLwQO40mM:-Knn8CRqapSBpRQ5ZX0p:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/models.py#L123)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

I think there is no need for `str()` around `service.name`
</blockquote></details>

Done.

---

*[ad_manager/models.py, line 133 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-KnimjoXgoWs4lZWoKOy:-KnnCf6kDFKKZ-2qLlgi:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/models.py#L133)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

`element_groups` would be a more fitting name
</blockquote></details>

Done.

---

*[ad_manager/models.py, line 152 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-KninSfCMV8jUIaRKnrJ:-KnnC_Ld94fFJVRvi2ET:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/models.py#L152)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

`for int_addr_idx, router_addr in router['InternalAddrs']:`
</blockquote></details>

Done.

---

*[ad_manager/models.py, line 153 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-KninuQNgIaZCfVCMlFy:-Knn4niOvsTFe-Y7kEJ-:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/models.py#L153)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

How about `for addr_attr in ADDR_ATTRIBUTES`? `SERVICE_ADDR_TYPES` seems to contain `Public` and `Bind` and for me the name was very misleading.
</blockquote></details>

Done.

---

*[ad_manager/models.py, line 154 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-KninqATzg3R9RlbrlAM:-KnneSpB8WtfIg3MVYGA:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/models.py#L154)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

no need for this anymore if you apply my change above
</blockquote></details>

Done.

---

*[ad_manager/models.py, line 193 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-KnipMpByalTqZYqWw5c:-Knn6MqRo2EZxQs4UBR6:b-r1d667) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/models.py#L193)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Shouldn't this be `bind_addr=intf['Bind']['Addr']`?
</blockquote></details>

Done. Good catch. I suppose that was a copy-paste mistake.

---

*[ad_manager/models.py, line 205 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-KnipX1aKBwWssfoUil5:-Knn5HU3aOZfZjc90GT2:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/models.py#L205)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

See comment above
</blockquote></details>

Done.

---

*[ad_manager/models.py, line 208 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-Knipo8gzuu3nKeJxtp-:-KnnmTr8O9pzXFTVLWrn:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/models.py#L208)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

`for addr_idx, addr_info in enumerate(service[attr])):`
</blockquote></details>

Done.

---

*[ad_manager/models.py, line 282 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-KniqQrI4rW4Ij6L78Dg:-KnnmXQzOGJbyaw9BlX7:b-raomj6) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/models.py#L282)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Is this somehow needed by the framework? Otherwise you can define an abstract class like this:
```
import abc

class AddressElement(models.Model, metaclass=abc.ABCMeta)
```
</blockquote></details>

Yes, this is a Django thing. The rest of the model declarations inside `models.py` have the same structure.

---

*[ad_manager/models.py, line 292 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-KnirVjMs9jUaiVlNhAC:-Kno5BykqSrd6YrVRzVc:b-3wkzus) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/models.py#L292)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

What does this do exactly? Right now it could be avoided I think, since a super class will already implement it and you don't do anything here. Same for other `get_dict` methods
</blockquote></details>

Done. Removed these as they are not used at the moment.

---

*[ad_manager/views.py, line 602 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-KnisNa7Z9-jafqpyNXL:-Knn5uFc4IHjpbXbxC46:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/views.py#L602)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

No need to define `lists_to_sort`
</blockquote></details>

Done.

---

*[ad_manager/views.py, line 1013 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-KnitxGRbioGR4fp_qwq:-Knnseuk2yREjiRfag83:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/views.py#L1013)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

```
for svc_type in service_types:
    for entry in topo_dict[svc_type]:
        for addr_info in entry['Public']:
            curr_pair = "%s:%s" % (addr_info['Addr'], addr_info['L4Port'])
```
</blockquote></details>

Done.

---

*[ad_manager/views.py, line 1020 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-Kniv7-vOCej4mdwPPv_:-KnnyUBHOokQEW1Bm3ye:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/views.py#L1020)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93)*

**Comment by shitz** [comment]
Review status: 10 of 18 files reviewed at latest revision, 3 unresolved discussions.

---

*[ad_manager/models.py, line 282 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-KniqQrI4rW4Ij6L78Dg:-KnoHMyTjxaaYHl0wOtk:big6d8q) ([raw file](https://github.com/netsec-ethz/scion-web/blob/17e6b4f2a2c4ae9dc86dc7d488ea3e4ec6ead6fd/ad_manager/models.py#L282)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Yes, this is a Django thing. The rest of the model declarations inside `models.py` have the same structure.
</blockquote></details>

Ok. I suspected that this was the case. Just wanted to make sure.

---

*[ad_manager/models.py, line 156 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-KnoGg0JlR3TKnxnXUnX:-KnoGg0JlR3TKnxnXUnY:b-rvpz41) ([raw file](https://github.com/netsec-ethz/scion-web/blob/901507aadf002e881a899e29e84a18739b7a09be/ad_manager/models.py#L156)):*
> ```Python
>                     if addr_attr not in router_addr.keys():
>                         continue
>                     for addr_idx in range(len(router_addr[addr_attr])):
> ```

You almost never have to use this type of for-loop. It's very un-pythony. If you need an index use `enumerate`

`for addr_idx, addr_info in enumerate(router_addr[addr_attr])`

(You changed it this way below btw)

---

*[ad_manager/views.py, line 1050 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-KnoI1GcrHAtt7ydNhNO:-KnoI1GcrHAtt7ydNhNP:b-deoiz) ([raw file](https://github.com/netsec-ethz/scion-web/blob/901507aadf002e881a899e29e84a18739b7a09be/ad_manager/views.py#L1050)):*
> ```Python
>     all_ip_port_pairs = []
>     for service_type in service_types:
>         for entry in topo_dict[service_type]:
> ```

If you changes this to `for entry in topo_dict[service_type].values()` you can use `for addr_info in entry['Public'].values()` below. My initial suggestion didn't include the `.values()`. You almost never should iterate over something and within the loop do the lookup for the element that you need.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93)*

**Comment by ercanucan** [comment]
Review status: 10 of 18 files reviewed at latest revision, 2 unresolved discussions.

---

*[ad_manager/models.py, line 156 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-KnoGg0JlR3TKnxnXUnX:-KnoP4_fG-ApFFxzGlVP:b-gkpxcr) ([raw file](https://github.com/netsec-ethz/scion-web/blob/901507aadf002e881a899e29e84a18739b7a09be/ad_manager/models.py#L156)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

You almost never have to use this type of for-loop. It's very un-pythony. If you need an index use `enumerate`

`for addr_idx, addr_info in enumerate(router_addr[addr_attr])`

(You changed it this way below btw)
</blockquote></details>

Done. (Yes, missed that one). Agree regarding `enumerate`. (CC'ing @jonghoonkwon.)

---

*[ad_manager/views.py, line 1050 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-KnoI1GcrHAtt7ydNhNO:-KnoPSSNGSkvNMXOghbb:b-ygazjy) ([raw file](https://github.com/netsec-ethz/scion-web/blob/901507aadf002e881a899e29e84a18739b7a09be/ad_manager/views.py#L1050)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

If you changes this to `for entry in topo_dict[service_type].values()` you can use `for addr_info in entry['Public'].values()` below. My initial suggestion didn't include the `.values()`. You almost never should iterate over something and within the loop do the lookup for the element that you need.
</blockquote></details>

Done. Just with a small difference that we don't do `entry['Public'].values()`, as `entry['Public']` is a `list`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93)*

**Comment by shitz** [comment]
:lgtm:

---

Reviewed 5 of 18 files at r1, 1 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ad_manager/models.py, line 152 at r4](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-KnobRxOHAuc2vSaGgWr:-KnobRxOHAuc2vSaGgWs:bfogcz0) ([raw file](https://github.com/netsec-ethz/scion-web/blob/01cb05d39eceb00a0c52f4451dba8854a2c4a167/ad_manager/models.py#L152)):*
> ```Python
>             br_obj, _ = BorderRouter.objects.update_or_create(name=name, ad=self)
>             br_addr_idx = []
>             for int_addr_idx, router_addr in enumerate(router['InternalAddrs']):
> ```

`int_addr_idx` is not used anymore I think.

---

*[ad_manager/views.py, line 1050 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-KnoI1GcrHAtt7ydNhNO:-KnobYdqNH7NR9127x4v:bbppgta) ([raw file](https://github.com/netsec-ethz/scion-web/blob/901507aadf002e881a899e29e84a18739b7a09be/ad_manager/views.py#L1050)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Done. Just with a small difference that we don't do `entry['Public'].values()`, as `entry['Public']` is a `list`.
</blockquote></details>

Ah ok. Missed that one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-:-Knobb4qgcONNGgVf7gX:bnfp4nl)*

**Comment by ercanucan** [comment]
Review status: 17 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[ad_manager/models.py, line 152 at r4](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93#-KnobRxOHAuc2vSaGgWr:-KnowhSqXw_fWTZGyoPu:bk7x8ld) ([raw file](https://github.com/netsec-ethz/scion-web/blob/01cb05d39eceb00a0c52f4451dba8854a2c4a167/ad_manager/models.py#L152)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

`int_addr_idx` is not used anymore I think.
</blockquote></details>

yes, you are right. cleaned it up.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93)*

**Comment by shitz** [comment]
Reviewed 2 of 3 files at r3, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/93)*

**Pull request merged**
