### PR TITLE
Create zlog files using the template.

### PR DESCRIPTION
**Pull request by ercanucan**
@FR4NK-W @kormat The zlog creation as per our discussions.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-web/33)

### CODE REVIEW

**Comment by kormat** [comment]
Looks good. Can you paste an example generated zlog config?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/33#-:-KRYsRgJU9JiClhGGidW:b-3tl2ql)*

**Comment by ercanucan** [comment]
@kormat Sure. 
Here is the file named br1-1-1.zlog.conf (under sub/web/gen/ISD1/AS1):
[global]
default format = "%d(%F %T).%us%d(%z) [%V] (%p:%c:%F:%L) %m%n"
file perms = 644

[rules]
default.* >stdout
router.DEBUG "logs/br1-1-1.zlog.DEBUG", 10MB*2
router.INFO "logs/br1-1-1.zlog.INFO", 10MB*2
router.WARN "logs/br1-1-1.zlog.WARNING", 10MB*2
router.ERROR "logs/br1-1-1.zlog.ERROR", 10MB*2
router.FATAL "logs/br1-1-1.zlog.CRITICAL", 10MB*2

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/33#-:-KRYtCv8jPhiR74c6REW:b-zi9qai)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/33#-:-KRYz57OQnI9SNUzRcTX:bnfp4nl)*

**Comment by ercanucan** [comment]
Thanks!

**Pull request merged**
