### PR TITLE
Modularize local_gen functions

### PR DESCRIPTION
**Pull request by jonghoonkwon**
@ercanucan, This is the modularization of the local_gen functions. It would be great if you have a look at it.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-web/104)

### CODE REVIEW

**Comment by ercanucan** [comment]
@jonghoonkwon made a pass. See my comments below. Please also do not forget to do linting.

---

Review status: 0 of 2 files reviewed at latest revision, 11 unresolved discussions.

---

*[ad_manager/util/local_config_generator.py, line 27 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-KqbBXq3NNGbGRH-EPf_:-KqbBXq3NNGbGRH-EPfa:bs89qew) ([raw file](https://github.com/netsec-ethz/scion-web/blob/8190919b5b813d5b3110bed2443f4ef728261dd3/ad_manager/util/local_config_generator.py#L27)):*
> ```Python
> 
> # SCION
> from lib.defines import PROJECT_ROOT, PROM_FILE
> ```

Please have the imports consistent with the rest of the code-base. In this case, something like:
```
from lib.defines import (
    PROJECT_ROOT,
    PROM_FILE,
)
```

---

*[ad_manager/util/local_config_generator.py, line 48 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-KqbCvAoxyMjKwoA7BHF:-KqbCvAoxyMjKwoA7BHG:bf3t91c) ([raw file](https://github.com/netsec-ethz/scion-web/blob/8190919b5b813d5b3110bed2443f4ef728261dd3/ad_manager/util/local_config_generator.py#L48)):*
> ```Python
>     write_topology_file,
>     write_zlog_file,
>     TYPES_TO_EXECUTABLES,
> ```

Please sort the imports.

---

*[ad_manager/util/local_config_generator.py, line 122 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-KqbDGWlJus-CtHttSwE:-KqbDGWlJus-CtHttSwF:b-v2assb) ([raw file](https://github.com/netsec-ethz/scion-web/blob/8190919b5b813d5b3110bed2443f4ef728261dd3/ad_manager/util/local_config_generator.py#L122)):*
> ```Python
> 
> 
> def _get_as_obj(isd_as):
> ```

Please add a comment to this function, so that we have it consistent with the rest of the code-base.

---

*[ad_manager/util/topo_gen.py, line 1 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-KqbDOjBLNf-nwWbsPMf:-KqbDOjBLNf-nwWbsPMg:bb6ht2h) ([raw file](https://github.com/netsec-ethz/scion-web/blob/8190919b5b813d5b3110bed2443f4ef728261dd3/ad_manager/util/topo_gen.py#L1)):*
> ```Python
> # Copyright 2014 ETH Zurich
> ```

2017

---

*[ad_manager/util/topo_gen.py, line 16 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-KqbG-X7DblSa4EiX77g:-KqbG-X7DblSa4EiX77h:b-pv03vx) ([raw file](https://github.com/netsec-ethz/scion-web/blob/8190919b5b813d5b3110bed2443f4ef728261dd3/ad_manager/util/topo_gen.py#L16)):*
> ```Python
> """
> :mod:`topo_generator` --- SCION topology generator
> ===========================================
> ```

minor: please have the underline go all the way until the end of the title text.

---

*[ad_manager/util/topo_gen.py, line 34 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-KqbDVv1Enhnprjx3PMB:-KqbDVv1Enhnprjx3PMC:bdxirgt) ([raw file](https://github.com/netsec-ethz/scion-web/blob/8190919b5b813d5b3110bed2443f4ef728261dd3/ad_manager/util/topo_gen.py#L34)):*
> ```Python
> from lib.crypto.trc import get_trc_file_path
> from lib.defines import (
> 	AS_CONF_FILE,
> ```

Please always use spaces in the Python code.

---

*[ad_manager/util/topo_gen.py, line 69 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-KqbDsU1-j0k9eB271-a:-KqbDsU1-j0k9eB271-b:bpczlsi) ([raw file](https://github.com/netsec-ethz/scion-web/blob/8190919b5b813d5b3110bed2443f4ef728261dd3/ad_manager/util/topo_gen.py#L69)):*
> ```Python
> }
> 
> class ASKeys(object):
> ```

Minor: The class name `ASKeys` is somewhat mis-leading, as it contains more than just the keys such as TRC and Cert. 

---

*[ad_manager/util/topo_gen.py, line 70 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-KqbDhrF3apSjMeH6F2X:-KqbDhrF3apSjMeH6F2Y:b-usg575) ([raw file](https://github.com/netsec-ethz/scion-web/blob/8190919b5b813d5b3110bed2443f4ef728261dd3/ad_manager/util/topo_gen.py#L70)):*
> ```Python
> 
> class ASKeys(object):
> 	"""
> ```

Please write a short comment about this class.

---

*[ad_manager/util/topo_gen.py, line 73 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-KqbE4frDAbL4ZeRJ17N:-KqbE4frDAbL4ZeRJ17O:b-v8l1co) ([raw file](https://github.com/netsec-ethz/scion-web/blob/8190919b5b813d5b3110bed2443f4ef728261dd3/ad_manager/util/topo_gen.py#L73)):*
> ```Python
> 	"""
> 	def __init__(self, sig_priv_key, enc_priv_key, certificate, trc, master_as_key):
> 		self.sig_priv_key = sig_priv_key
> ```

Please always use spaces.

---

*[ad_manager/util/topo_gen.py, line 251 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-KqbEqBfHK_p2lUneucK:-KqbEqBfHK_p2lUneucL:bpri74) ([raw file](https://github.com/netsec-ethz/scion-web/blob/8190919b5b813d5b3110bed2443f4ef728261dd3/ad_manager/util/topo_gen.py#L251)):*
> ```Python
> 
> 
> def write_certs_trc_keys(isd_as, as_obj, instance_path):
> ```

I thought we wanted to make these functions independent of the Django model objects, so that the clients of these libraries can use them outside of Django framework, such as scion-coord or scion lab update gen scripts. They will not be able to pass in an AS model object. Or is the idea for outside clients of the library to create an `ASKeys` object and pass that in?

---

*[ad_manager/util/topo_gen.py, line 273 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-KqbFO9n3WOkOUxxuwh_:-KqbFO9oYKzllajC_Ka3:brhumzt) ([raw file](https://github.com/netsec-ethz/scion-web/blob/8190919b5b813d5b3110bed2443f4ef728261dd3/ad_manager/util/topo_gen.py#L273)):*
> ```Python
> 
> 
> def write_as_conf_and_path_policy(isd_as, as_obj, instance_path):
> ```

Same here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-:-KqbGM-W5EsBGumTN4rX:burqfiy)*

**Comment by ercanucan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 11 unresolved discussions.

---

*[ad_manager/util/topo_gen.py, line 16 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-KqbG-X7DblSa4EiX77g:-KqbH88bNZZIiVg7BNIl:b3gmte4) ([raw file](https://github.com/netsec-ethz/scion-web/blob/8190919b5b813d5b3110bed2443f4ef728261dd3/ad_manager/util/topo_gen.py#L16)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

minor: please have the underline go all the way until the end of the title text.
</blockquote></details>

Please also add a short description as to what this library provides.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104)*

**Comment by jonghoonkwon** [comment]
Review status: 0 of 2 files reviewed at latest revision, 11 unresolved discussions.

---

*[ad_manager/util/local_config_generator.py, line 27 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-KqbBXq3NNGbGRH-EPf_:-KqbLM4LreuXAhECcjkp:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/8190919b5b813d5b3110bed2443f4ef728261dd3/ad_manager/util/local_config_generator.py#L27)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Please have the imports consistent with the rest of the code-base. In this case, something like:
```
from lib.defines import (
    PROJECT_ROOT,
    PROM_FILE,
)
```
</blockquote></details>

Done.

---

*[ad_manager/util/local_config_generator.py, line 48 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-KqbCvAoxyMjKwoA7BHF:-KqbOYE9na309qPcG8id:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/8190919b5b813d5b3110bed2443f4ef728261dd3/ad_manager/util/local_config_generator.py#L48)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Please sort the imports.
</blockquote></details>

Done.

---

*[ad_manager/util/local_config_generator.py, line 122 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-KqbDGWlJus-CtHttSwE:-KqbMFm4ctdknn8rWLyx:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/8190919b5b813d5b3110bed2443f4ef728261dd3/ad_manager/util/local_config_generator.py#L122)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Please add a comment to this function, so that we have it consistent with the rest of the code-base.
</blockquote></details>

Done.

---

*[ad_manager/util/topo_gen.py, line 1 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-KqbDOjBLNf-nwWbsPMf:-KqbMOUpEgKUjrbO1Upq:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/8190919b5b813d5b3110bed2443f4ef728261dd3/ad_manager/util/topo_gen.py#L1)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

2017
</blockquote></details>

Done.

---

*[ad_manager/util/topo_gen.py, line 16 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-KqbG-X7DblSa4EiX77g:-KqbN8OAGR5h970Ilg2m:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/8190919b5b813d5b3110bed2443f4ef728261dd3/ad_manager/util/topo_gen.py#L16)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Please also add a short description as to what this library provides.
</blockquote></details>

Done.

---

*[ad_manager/util/topo_gen.py, line 34 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-KqbDVv1Enhnprjx3PMB:-KqbNSTabvYUOc0k9_VD:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/8190919b5b813d5b3110bed2443f4ef728261dd3/ad_manager/util/topo_gen.py#L34)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Please always use spaces in the Python code.
</blockquote></details>

Done.

---

*[ad_manager/util/topo_gen.py, line 69 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-KqbDsU1-j0k9eB271-a:-KqbOIw56Rpc4_XXevTH:b-tvzsce) ([raw file](https://github.com/netsec-ethz/scion-web/blob/8190919b5b813d5b3110bed2443f4ef728261dd3/ad_manager/util/topo_gen.py#L69)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Minor: The class name `ASKeys` is somewhat mis-leading, as it contains more than just the keys such as TRC and Cert. 
</blockquote></details>

Any suggestion?

---

*[ad_manager/util/topo_gen.py, line 70 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-KqbDhrF3apSjMeH6F2X:-KqbPaKZ_1K3QLkVYUrP:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/8190919b5b813d5b3110bed2443f4ef728261dd3/ad_manager/util/topo_gen.py#L70)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Please write a short comment about this class.
</blockquote></details>

Done.

---

*[ad_manager/util/topo_gen.py, line 73 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-KqbE4frDAbL4ZeRJ17N:-KqbObismCfnbPF2lDR6:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/8190919b5b813d5b3110bed2443f4ef728261dd3/ad_manager/util/topo_gen.py#L73)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Please always use spaces.
</blockquote></details>

Done.

---

*[ad_manager/util/topo_gen.py, line 251 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-KqbEqBfHK_p2lUneucK:-KqbPuCgQdKjicA4dLgL:b-1cuwcl) ([raw file](https://github.com/netsec-ethz/scion-web/blob/8190919b5b813d5b3110bed2443f4ef728261dd3/ad_manager/util/topo_gen.py#L251)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

I thought we wanted to make these functions independent of the Django model objects, so that the clients of these libraries can use them outside of Django framework, such as scion-coord or scion lab update gen scripts. They will not be able to pass in an AS model object. Or is the idea for outside clients of the library to create an `ASKeys` object and pass that in?
</blockquote></details>

The as_obj parameter was intended to be either the Django model object or ASKeys object. The clients using Django framework are able to pass the model object in, while the other clients are able to create the ASKeys object and pass it in. 

---

*[ad_manager/util/topo_gen.py, line 273 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-KqbFO9n3WOkOUxxuwh_:-KqbS8wgU9bnOujIEn8C:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/8190919b5b813d5b3110bed2443f4ef728261dd3/ad_manager/util/topo_gen.py#L273)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104)*

**Comment by ercanucan** [comment]
@jonghoonkwon did you push the changes? I only see the comments but not the modifications.

---

Review status: 0 of 2 files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-:-KqbsNTnrtE-5JJrPuS0:b-v3ynv8)*

**Comment by ercanucan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 12 unresolved discussions.

---

*[ad_manager/util/local_config_generator.py, line 15 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-KqcAG8lMFb-G0dKM7qq:-KqcAG8mLzAcRFusY6vl:bnsj1g0) ([raw file](https://github.com/netsec-ethz/scion-web/blob/7ffcf689f427b5bf15f65c969c159dd26a154cb3/ad_manager/util/local_config_generator.py#L15)):*
> ```Python
> # limitations under the License.
> """
> :mod:`local_config_generator` --- Local config generator tool for a SCIONLab VM
> ```

We should change this comment, because the `local_config_generator` is used from within scion-web, it's not related to SCIONLab VM creation.

---

*[ad_manager/util/topo_gen.py, line 16 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-KqbG-X7DblSa4EiX77g:-KqcAbPppx6hUXjK6phH:btngkip) ([raw file](https://github.com/netsec-ethz/scion-web/blob/8190919b5b813d5b3110bed2443f4ef728261dd3/ad_manager/util/topo_gen.py#L16)):*
<details><summary><i>Previously, jonghoonkwon wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Let's add a small description here why we separated out these functions to a library that could be used independently without running scion-web itself (i.e. in order to use the library functions from services such as scion-coord, without having to run the whole scion-web instance on that machine)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104)*

**Comment by ercanucan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 13 unresolved discussions.

---

*[ad_manager/util/topo_gen.py, line 1 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-KqcBUsQ_92fNtvp5mTZ:-KqcBUsRbnuwS739huyz:b6seh2h) ([raw file](https://github.com/netsec-ethz/scion-web/blob/7ffcf689f427b5bf15f65c969c159dd26a154cb3/ad_manager/util/topo_gen.py#L1)):*
> ```Python
> # Copyright 2017 ETH Zurich
> ```

How about renaming this file to `local_config_util`? Because it's not only generating the topo file but also doing other things.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104)*

**Comment by jonghoonkwon** [comment]
Review status: 0 of 2 files reviewed at latest revision, 9 unresolved discussions.

---

*[ad_manager/util/local_config_generator.py, line 15 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-KqcAG8lMFb-G0dKM7qq:-KqcFeeTixE1QDFuRVsA:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/7ffcf689f427b5bf15f65c969c159dd26a154cb3/ad_manager/util/local_config_generator.py#L15)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

We should change this comment, because the `local_config_generator` is used from within scion-web, it's not related to SCIONLab VM creation.
</blockquote></details>

Done.

---

*[ad_manager/util/topo_gen.py, line 16 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-KqbG-X7DblSa4EiX77g:-KqcH3vPBi072KitzOEV:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/8190919b5b813d5b3110bed2443f4ef728261dd3/ad_manager/util/topo_gen.py#L16)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Let's add a small description here why we separated out these functions to a library that could be used independently without running scion-web itself (i.e. in order to use the library functions from services such as scion-coord, without having to run the whole scion-web instance on that machine)
</blockquote></details>

Done.

---

*[ad_manager/util/topo_gen.py, line 1 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-KqcBUsQ_92fNtvp5mTZ:-KqcFqjA_ezHwuUFyVfL:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/7ffcf689f427b5bf15f65c969c159dd26a154cb3/ad_manager/util/topo_gen.py#L1)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

How about renaming this file to `local_config_util`? Because it's not only generating the topo file but also doing other things.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104)*

**Comment by ercanucan** [comment]
:lgtm: Tested it and confirmed it works as expected. Please squash the commits into one and let's merge it.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-:-KqcTvDyhdvlfloyFnj_:bblu0pt)*

**Comment by jonghoonkwon** [comment]
Thx

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104#-:-KqcVIJzlpkBaWBQHfN0:b2nhpa7)*

**Comment by ercanucan** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/104)*

**Comment by ercanucan** [comment]
merging.

**Pull request merged**
