### PR TITLE
Adapts scion-web's cert generation to changes in the main repo.

### PR DESCRIPTION
**Pull request by ercanucan**
Also fixes a small UI bug introduced from the new topo update.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-web/102)

### CODE REVIEW

**Comment by ercanucan** [comment]
@jonghoonkwon @shitz

**Comment by shitz** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/102#-:-KobaTfCDkThZU4P6g10:bnfp4nl)*

**Comment by jonghoonkwon** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/102#-:-KobdRQNrZ7dHLmc8dik:bnfp4nl)*

**Comment by ercanucan** [comment]
thx!

**Pull request merged**
