### PR TITLE
Add licence information into scion-web files.

### PR DESCRIPTION
**Pull request by ercanucan**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-web/36)

### CODE REVIEW

**Comment by ercanucan** [comment]
@pszalach @klausman I've added the license text into a few files which did not have them yet.

**Comment by klausman** [comment]
Is our intent to eventually opensource scion-web? I wasn't aware of that.

---

Review status: 0 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/36#-:-KSl4HHzwaNbBx-YHzAW:bgui7xn)*

**Comment by ercanucan** [comment]
It's already a public repo :-)

**Comment by klausman** [comment]
:lgtm: Oh, carry on, then.

---

Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/36#-:-KSl5E8PkKOuQAsa0oxG:b-ud29ur)*

**Comment by ercanucan** [comment]
Thanks!

**Pull request merged**
