### PR TITLE
Generating supervisor configuration for sciond

### PR DESCRIPTION
**Pull request by jonghoonkwon**
Addressed #80

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-web/116)

### CODE REVIEW

**Comment by jonghoonkwon** [comment]
@shitz, it would be nice if you have a moment to look at this :)

**Comment by mlegner** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[ad_manager/util/local_config_util.py, line 314 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/116#-L0smOtWVrIwIXG2IVG1:-L0smOtWVrIwIXG2IVG2:b-wnznfy) ([raw file](https://github.com/netsec-ethz/scion-web/blob/fd1b2b972dac623ae7fbf1986b7ecc24bff7ac69/ad_manager/util/local_config_util.py#L314)):*
> ```Python
> 
> 
> def gererate_sciond_config(isd_as, as_obj, tp):
> ```

I would call this "generate_sciond_config".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/116)*

**Comment by jonghoonkwon** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[ad_manager/util/local_config_util.py, line 314 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/116#-L0smOtWVrIwIXG2IVG1:-L12VEnMPE3K4zistW_X:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/fd1b2b972dac623ae7fbf1986b7ecc24bff7ac69/ad_manager/util/local_config_util.py#L314)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

I would call this "generate_sciond_config".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/116)*

**Comment by jonghoonkwon** [comment]
@mlegner, Many thanks for the comment. If you don't mind, I'm going to merge it to master branch.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/116#-:-L12Vh7LQ5_lDO_KXNfD:b-h1f8xw)*

**Comment by jonghoonkwon** [comment]
@mlegner, please resolve the discussions on Reviwable so that I can merge it.

**Comment by jonghoonkwon** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/116)*

**Comment by mlegner** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/116#-:-L4540IA7Vp_c4JPOvCD:bnfp4nl)*

**Pull request merged**
