### PR TITLE
Credentials update utility.

### PR DESCRIPTION
**Pull request by ercanucan**
This is a simple utility tool to update credentials stored in
scion-web's database from a given directory, for a given ISD.

The tool will update the following entries in the given ISD:
- AS Certificate
- TRC
- Enc Signing Key
- Priv Signing Key
- Master AS Key

The tools assumes that the provided directory structure looks like a typical
gen folder that's generated via generator.py or scion-web.

Example usage:

python3 ./scripts/update_credentials.py --dir=<path_to_isd_folder> --isd=2

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-web/110)

### CODE REVIEW

**Comment by ercanucan** [comment]
@jonghoonkwon here is the first draft.

**Comment by jonghoonkwon** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[scripts/update_credentials.py, line 81 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/110#-KxCSfl0yRtRtvWUy1q_:-KxCSfl10covUHGhnImf:burgv1l) ([raw file](https://github.com/netsec-ethz/scion-web/blob/5609df4825ba1d443da6a50bd0acf258ffe4e1b4/scripts/update_credentials.py#L81)):*
> ```Python
>     with open(file_path) as json_file:
>         json_data = json.load(json_file)
>         res = json.dumps(json_data, indent=4, sort_keys=True, separators=(',', ': '))
> ```

In main codebase, as Sam recommended, we use 'indent=2' for json dumps. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/110#-:-KxCTdrZL-MjQ5MZaWtg:bnfp4nl)*

**Comment by ercanucan** [comment]
@jonghoonkwon responded to your feedback, also added some comments to the code.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[scripts/update_credentials.py, line 81 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/110#-KxCSfl0yRtRtvWUy1q_:-KxD9wzXb-rktQzZKGPF:b-4rx5ve) ([raw file](https://github.com/netsec-ethz/scion-web/blob/5609df4825ba1d443da6a50bd0acf258ffe4e1b4/scripts/update_credentials.py#L81)):*
<details><summary><i>Previously, jonghoonkwon wrote…</i></summary><blockquote>

In main codebase, as Sam recommended, we use 'indent=2' for json dumps. 
</blockquote></details>

I see. I can do that, but the looking at the main code-base, both the certificates and TRCs are generated with 4 space indents.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/110#-:-KxDBtj7LpQr0VCym7W2:bydop43)*

**Comment by jonghoonkwon** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/110)*

**Comment by ercanucan** [comment]
thx! merging

**Pull request merged**
