### PR TITLE
Prometheous configuration for bind address 

### PR DESCRIPTION
**Pull request by jonghoonkwon**
@ercanucan: It would be nice if you have a chance to look at this.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-web/112)

### CODE REVIEW

**Comment by ercanucan** [comment]
@jonghoonkwon made a pass. I see that it also contains the exact content of PR https://github.com/netsec-ethz/scion-web/pull/111. So it would be good to those bits out.

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[ad_manager/util/local_config_generator.py, line 145 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/112#-KxNbBS3lmEkmR5VRiC_:-KxNbBS49bJZ9LkBMp3t:bdfagso) ([raw file](https://github.com/netsec-ethz/scion-web/blob/fb84c2dc3351b726680f6613d354e68af26a033d/ad_manager/util/local_config_generator.py#L145)):*
> ```Python
>     """
>     elem_dict = defaultdict(list)
>     print(tp)
> ```

Looks like a debug print. I think we don't need this.

---

*[ad_manager/util/local_config_generator.py, line 154 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/112#-KxNbSYZWZ35Ut8OFi0c:-KxNbSYZWZ35Ut8OFi0d:bfj814f) ([raw file](https://github.com/netsec-ethz/scion-web/blob/fb84c2dc3351b726680f6613d354e68af26a033d/ad_manager/util/local_config_generator.py#L154)):*
> ```Python
>     for svc_type in ['BeaconService', 'PathService', 'CertificateService']:
>         for elem_id, elem in tp[svc_type].items():
>             addr_type = 'Bind' if 'Bind' in elem.keys() else 'Public'
> ```

minor: I think we should make this a function, as we are calling it repeatedly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/112#-:-KxNbfQzBH4hyaVo8Qei:bkdotup)*

**Comment by ercanucan** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/112#-:-KxhUKMw_heLP2FFjeYF:bnfp4nl)*

**Comment by jonghoonkwon** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[ad_manager/util/local_config_generator.py, line 145 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/112#-KxNbBS3lmEkmR5VRiC_:-KxhTcJbdBEvcas70gFG:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/fb84c2dc3351b726680f6613d354e68af26a033d/ad_manager/util/local_config_generator.py#L145)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Looks like a debug print. I think we don't need this.
</blockquote></details>

Done.

---

*[ad_manager/util/local_config_generator.py, line 154 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/112#-KxNbSYZWZ35Ut8OFi0c:-KxhU4bmHoNQXUtUteQm:b-3s4wpx) ([raw file](https://github.com/netsec-ethz/scion-web/blob/fb84c2dc3351b726680f6613d354e68af26a033d/ad_manager/util/local_config_generator.py#L154)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

minor: I think we should make this a function, as we are calling it repeatedly.
</blockquote></details>

I'll make the function if it is needed again in future.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/112)*

**Comment by ercanucan** [comment]
Reviewed 1 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/112)*

**Pull request merged**
