### PR TITLE
EdgeRouter to BoderRouter and new name format

### PR DESCRIPTION
**Pull request by FR4NK-W**
@ercanucan @pszalach Small pull request to rename edge router to border router and close Github issue #6

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-web/8)

### CODE REVIEW

**Comment by ercanucan** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[ad_manager/static/js/topology_input.js, line 154 \[r1\]](https://reviewable.io:443/reviews/netsec-ethz/scion-web/8#-KPNOVuZ9XFjf2qXtnRS:-KPNOVu_VId91RkSgahm:b4273qx) ([raw file](https://github.com/netsec-ethz/scion-web/blob/cd6e15a77fc18551a8236378ca5e2cbde721bdf6/ad_manager/static/js/topology_input.js#L154)):*
> ```JavaScript
>     }
> 
>     var borderRouterIndex = 0;
> ```

in the future I would consider splitting this function into smaller function. looks a bit large right now. we can do this as a separate PR as part of https://github.com/netsec-ethz/scion-web/issues/4

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/8)*

**Comment by ercanucan** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/8#-:-KPNQ2dnwIfTjtzWIIBb:bnfp4nl)*

**Comment by pszalach** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/8#-:-KPSPHkBHmAhMwuiwoi-:bnfp4nl)*

**Comment by FR4NK-W** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[ad_manager/static/js/topology_input.js, line 154 \[r1\]](https://reviewable.io:443/reviews/netsec-ethz/scion-web/8#-KPNOVuZ9XFjf2qXtnRS:-KPSS1LUUbPw7COuf4Yx:bpgnfhy) ([raw file](https://github.com/netsec-ethz/scion-web/blob/cd6e15a77fc18551a8236378ca5e2cbde721bdf6/ad_manager/static/js/topology_input.js#L154)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary>
> in the future I would consider splitting this function into smaller function. looks a bit large right now. we can do this as a separate PR as part of https://github.com/netsec-ethz/scion-web/issues/4
</details>
Already done as part of #4 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/8)*

**Comment by ercanucan** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/8)*

**Pull request merged**
