### PR TITLE
Git code version field for deployment

### PR DESCRIPTION
**Pull request by FR4NK-W**
@ercanucan @pszalach Pull request to close issue #2 to enable the user to select or type in which code version to deploy.
Retrieves commit hashes via the Github API and sets it in the Ansible hostfile

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-web/9)

### CODE REVIEW

**Comment by FR4NK-W** [comment]
edited to change PR stacking to make review easier

**Comment by pszalach** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/9#-:-KPSRdoSR1REKgZru5ef:bnfp4nl)*

**Comment by ercanucan** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[ad_manager/static/js/ad_detail.js, line 243 \[r1\]](https://reviewable.io:443/reviews/netsec-ethz/scion-web/9#-KPSYSv-m4mU-gkMveRy:-KPSYSv-m4mU-gkMveRz:b-3wlkik) ([raw file](https://github.com/netsec-ethz/scion-web/blob/79e795df5a2e61fbe97690d98227318bdc5a1d55/ad_manager/static/js/ad_detail.js#L243)):*
> ```JavaScript
>     var organisation = "/netsec-ethz";
>     var repo = "/scion-web/"; // set this to the main scion repo aka /scion/ one it is public
>     var numberOfResults = 5;
> ```

5 seems to a bit too small number of results for a realistic usage scenario. Can we do something like "show me the commits in the last 2 weeks (or month) etc". This would make it more usable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/9)*

**Comment by ercanucan** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[ad_manager/templates/ad_manager/ad_detail.html, line 173 \[r1\]](https://reviewable.io:443/reviews/netsec-ethz/scion-web/9#-KPSYteizW3UOIqp71mM:-KPSYteizW3UOIqp71mN:bj30nes) ([raw file](https://github.com/netsec-ethz/scion-web/blob/79e795df5a2e61fbe97690d98227318bdc5a1d55/ad_manager/templates/ad_manager/ad_detail.html#L173)):*
> ```HTML
>                   Deploy the saved configuration with Ansible:
>                   <br/>
>                   <label for="commitHash" >Use the code of the commit with this hash:</label>
> ```

I would just say "Version to deploy from github" or something simple like that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/9)*

**Comment by FR4NK-W** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[ad_manager/static/js/ad_detail.js, line 243 \[r1\]](https://reviewable.io:443/reviews/netsec-ethz/scion-web/9#-KPSYSv-m4mU-gkMveRy:-KPX9Kz1ne0pQTkwfkv5:biacs76) ([raw file](https://github.com/netsec-ethz/scion-web/blob/79e795df5a2e61fbe97690d98227318bdc5a1d55/ad_manager/static/js/ad_detail.js#L243)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary>
> 5 seems to a bit too small number of results for a realistic usage scenario. Can we do something like "show me the commits in the last 2 weeks (or month) etc". This would make it more usable.
</details>
Addressed in commit 0a25435

---

*[ad_manager/templates/ad_manager/ad_detail.html, line 173 \[r1\]](https://reviewable.io:443/reviews/netsec-ethz/scion-web/9#-KPSYteizW3UOIqp71mM:-KPXAuRhsUhn2ANASwaz:biacs76) ([raw file](https://github.com/netsec-ethz/scion-web/blob/79e795df5a2e61fbe97690d98227318bdc5a1d55/ad_manager/templates/ad_manager/ad_detail.html#L173)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary>
> I would just say "Version to deploy from github" or something simple like that.
</details>
Addressed in commit 0a25435

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/9)*

**Comment by ercanucan** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/9#-:-KPXxMXuQg71l1XiF49J:bnfp4nl)*

**Comment by ercanucan** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/9)*

**Pull request merged**
