### PR TITLE
Adapt BR_TARGET file to new Prometheus metrics changes.

### PR DESCRIPTION
**Pull request by ercanucan**
PR https://github.com/netsec-ethz/scion/pull/1135 changed the BR_TARGET_FILE string
to TARGET_FILES dictionary.

This change is necessary to make current scion-web version compliant with the master of main repository.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-web/94)

### CODE REVIEW

**Comment by ercanucan** [comment]
@shitz

**Comment by shitz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/94#-:-Ko7JKnV0Tt_C7P8P1Zl:bnfp4nl)*

**Comment by ercanucan** [comment]
thx!

**Comment by shitz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[ad_manager/util/local_config_generator.py, line 357 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/94#-Ko7aDQbZ7emn83dy9_t:-Ko7aDQbZ7emn83dy9_u:bwmelsx) ([raw file](https://github.com/netsec-ethz/scion-web/blob/4603b5834ae7a7c93f2d9ba29da9d0a4dcb68598/ad_manager/util/local_config_generator.py#L357)):*
> ```Python
>         targets_path = os.path.join(
>             get_elem_dir(local_gen_path, ia, ""),
>             PrometheusGenerator.PROM_DIR, PrometheusGenerator.TARGET_FILES["BorderRouters"])
> ```

I'm sorry I missed this, but this is actually not correct. What you want to use here is `PROM_FILE` not a target file. I will fix it in my PR anyway so you might leave it for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/94)*

**Comment by shitz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ad_manager/util/local_config_generator.py, line 357 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/94#-Ko7aDQbZ7emn83dy9_t:-Ko7eF8yGXKVanZO0mY5:bybhrt4) ([raw file](https://github.com/netsec-ethz/scion-web/blob/4603b5834ae7a7c93f2d9ba29da9d0a4dcb68598/ad_manager/util/local_config_generator.py#L357)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

I'm sorry I missed this, but this is actually not correct. What you want to use here is `PROM_FILE` not a target file. I will fix it in my PR anyway so you might leave it for now.
</blockquote></details>

Nevermind this is correct. My bad. Sorry!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/94)*

**Pull request merged**
