### PR TITLE
Prometheus configuration for border routers and refactor views.py.

### PR DESCRIPTION
**Pull request by ercanucan**
Prometheus configuration for border routers and refactoring of views.py.
This PR includes the following:
- Moves local config generation related code into util/local_config_generator.py
in order to avoid having a very large views.py
- Adds two more functions to local_config_generator.py for generating Prometheus
configuration files for border routers. Depends on:
https://github.com/netsec-ethz/scion/pull/1033

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-web/75)

### CODE REVIEW

**Comment by ercanucan** [comment]
@FR4NK-W, (@klausman or @kormat). @hausheer If you like to try this PR out, please feel free to do so.

**Comment by ercanucan** [comment]
@forstern

**Comment by kormat** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[ad_manager/util/local_config_generator.py, line 59 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-Kh22LRqsTKuUtYrXqWt:-Kh22LRqsTKuUtYrXqWu:b-wurbhy) ([raw file](https://github.com/netsec-ethz/scion-web/blob/3ea56250fa9d082e944bebdbf32ddf81d48a7635/ad_manager/util/local_config_generator.py#L59)):*
> ```Python
> ZOOKEEPER_SERVICE = "zk"  # TODO: make PR to add into lib.defines as it used to
> # Scion beacon server
> BEACON_EXECUTABLE = "beacon_server"
> ```

These all seem to be only referenced once - in the dict mapping service to executable. In that case, you might as well just put the literals into the dict, and not define them separately.

---

*[ad_manager/util/local_config_generator.py, line 67 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-Kh2S6oVAY0eRAMVUbPk:-Kh2S6oVAY0eRAMVUbPl:b-ygbyxy) ([raw file](https://github.com/netsec-ethz/scion-web/blob/3ea56250fa9d082e944bebdbf32ddf81d48a7635/ad_manager/util/local_config_generator.py#L67)):*
> ```Python
> SIBRA_EXECUTABLE = "sibra_server"
> # Scion border router
> ROUTER_EXECUTABLE = "router"
> ```

This isn't correct (and isn't used, apparently).

---

*[ad_manager/util/local_config_generator.py, line 69 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-Kh2KlYUVaiWlZCegDEj:-Kh2KlYUVaiWlZCegDEk:bjtemc9) ([raw file](https://github.com/netsec-ethz/scion-web/blob/3ea56250fa9d082e944bebdbf32ddf81d48a7635/ad_manager/util/local_config_generator.py#L69)):*
> ```Python
> ROUTER_EXECUTABLE = "router"
> # Zookeeper executable
> ZOOKEEPER_EXECUTABLE = "zookeeper.jar"
> ```

As scion-web doesn't handle managed zookeeper instances, why is this needed/used?

---

*[ad_manager/util/local_config_generator.py, line 85 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-Kh21SOC-8P54F0s9q-T:-Kh21SOD7uvx5ycZqLsW:b-ew4u8h) ([raw file](https://github.com/netsec-ethz/scion-web/blob/3ea56250fa9d082e944bebdbf32ddf81d48a7635/ad_manager/util/local_config_generator.py#L85)):*
> ```Python
> 
> 
> def lookup_dict_services_prefixes():
> ```

Why a function to return a static dict? It would be more straight-forward to just declare the dicts as module-level constants. (Same for `lookup_dict_executables`).

---

*[ad_manager/util/local_config_generator.py, line 127 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-Kh24KZD-qytaP2LbKLf:-Kh24KZD-qytaP2LbKLg:b-k5mib9) ([raw file](https://github.com/netsec-ethz/scion-web/blob/3ea56250fa9d082e944bebdbf32ddf81d48a7635/ad_manager/util/local_config_generator.py#L127)):*
> ```Python
>     dict_keys = ['BeaconServers', 'CertificateServers', 'BorderRouters',
>                  'PathServers', 'SibraServers', 'Zookeepers']
>     types_keys = zip(types, dict_keys)
> ```

As this is a strictly one-to-one mapping, i would just use a single dict. `{"beacon_server": "BeaconServers"....}`

---

*[ad_manager/util/local_config_generator.py, line 131 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-Kh2Qccnr8O1ZMpx_MUS:-Kh2Qccnr8O1ZMpx_MUT:bkqwqmp) ([raw file](https://github.com/netsec-ethz/scion-web/blob/3ea56250fa9d082e944bebdbf32ddf81d48a7635/ad_manager/util/local_config_generator.py#L131)):*
> ```Python
>     for service_type, type_key in types_keys:
>         executable_name = lkx[service_type]
>         replicas = tp[type_key].keys()  # SECURITY WARNING:allows arbitrary path
> ```

What is a "replica"?

---

*[ad_manager/util/local_config_generator.py, line 133 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-Kh2Q4xQ5i1TzELXkTCv:-Kh2Q4xQ5i1TzELXkTCw:b-656lhu) ([raw file](https://github.com/netsec-ethz/scion-web/blob/3ea56250fa9d082e944bebdbf32ddf81d48a7635/ad_manager/util/local_config_generator.py#L133)):*
> ```Python
>         replicas = tp[type_key].keys()  # SECURITY WARNING:allows arbitrary path
>         # the user can enter arbitrary paths for his output
>         # Mitigation: make path at least relative
> ```

I don't understand this. The paths and executable names are hard-coded in this file. What is this actually trying to protect against?

---

*[ad_manager/util/local_config_generator.py, line 205 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-Kh2ScrVq6Jaq5iIPai2:-Kh2ScrVq6Jaq5iIPai3:bpid7rj) ([raw file](https://github.com/netsec-ethz/scion-web/blob/3ea56250fa9d082e944bebdbf32ddf81d48a7635/ad_manager/util/local_config_generator.py#L205)):*
> ```Python
>     """
>     config = configparser.ConfigParser()
>     env_tmpl = 'PYTHONPATH=.,ZLOG_CFG="gen/ISD%s/AS%s/%s/%s.zlog.conf"'
> ```

I could three places in this function alone where `gen/ISD%s/AS%s/%s/` is calculated, and about 8 total in this file :/ How about adding a simple utility function like:
```
def get_elem_dir(isd_as, elem_id):
  return "%s/ISD%s/AS%s/%s" % (GEN_PATH, isd_as[0], isd_as[1], elem_id)
```

---

*[ad_manager/util/local_config_generator.py, line 209 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-Kh2SIdBggUOb_MBcrBA:-Kh2SIdBggUOb_MBcrBB:b-dt5fi8) ([raw file](https://github.com/netsec-ethz/scion-web/blob/3ea56250fa9d082e944bebdbf32ddf81d48a7635/ad_manager/util/local_config_generator.py#L209)):*
> ```Python
>         env_tmpl += ',GODEBUG="cgocheck=0"'
>         cmd_tmpl = ('bash -c \'exec "bin/border" "-id" "%s" "-confd" '
>                     '"gen/ISD%s/AS%s/%s" &>logs/%s.OUT\'')
> ```

There's no need to use so many quotes. There's also no need to define the template separately, especially when it's re-defined every time.
```
cmd = "bash -c 'exec bin/border -id "%s" -confd "%s" &>logs/%s.OUT'" % (
    instance_name, elem_dir, instance_name)
```

---

*[ad_manager/util/local_config_generator.py, line 212 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-Kh2Uswra02wu1Jx549w:-Kh2Uswra02wu1Jx549x:b-4s2sql) ([raw file](https://github.com/netsec-ethz/scion-web/blob/3ea56250fa9d082e944bebdbf32ddf81d48a7635/ad_manager/util/local_config_generator.py#L212)):*
> ```Python
>         cmd = cmd_tmpl % (instance_name, isd_id, as_id,
>                           instance_name, instance_name)
>     elif service_type == 'zookeeper_service':
> ```

I think this can be dropped.

---

*[ad_manager/util/local_config_generator.py, line 216 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-Kh2V--BJ7C9vkWPNzci:-Kh2V--BJ7C9vkWPNzcj:b2nreh6) ([raw file](https://github.com/netsec-ethz/scion-web/blob/3ea56250fa9d082e944bebdbf32ddf81d48a7635/ad_manager/util/local_config_generator.py#L216)):*
> ```Python
>     else:  # other infrastructure elements
>         cmd_tmpl = ('bash -c \'exec "bin/%s" "%s" '
>                     '"gen/ISD%s/AS%s/%s" &>logs/%s.OUT\'')
> ```

Same as above.

---

*[ad_manager/util/local_config_generator.py, line 221 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-Kh2V4D6l2oJsCCsZoRe:-Kh2V4D6l2oJsCCsZoRf:b-lj1ikv) ([raw file](https://github.com/netsec-ethz/scion-web/blob/3ea56250fa9d082e944bebdbf32ddf81d48a7635/ad_manager/util/local_config_generator.py#L221)):*
> ```Python
>     env = env_tmpl % (isd_id, as_id, instance_name, instance_name)
>     config['program:' + instance_name] = {
>         'priority': '100',
> ```

These are in a random order, making it hard to read. I suggest you use a similar order to https://github.com/netsec-ethz/scion/blob/master/topology/generator.py#L798

---

*[ad_manager/util/local_config_generator.py, line 421 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-Kh2WXY9VhTLREVlCvoO:-Kh2WXY9VhTLREVlCvoP:b-j9p7dr) ([raw file](https://github.com/netsec-ethz/scion-web/blob/3ea56250fa9d082e944bebdbf32ddf81d48a7635/ad_manager/util/local_config_generator.py#L421)):*
> ```Python
>     router_list = []
>     routers = tp['BorderRouters']
>     for _, router in routers.items():
> ```

`for router in tp['BorderRouters'].values():`

---

*[ad_manager/util/local_config_generator.py, line 450 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-Kh2XGXcyfL9kVkw70Sq:-Kh2XGXcyfL9kVkw70Sr:bb7bbs7) ([raw file](https://github.com/netsec-ethz/scion-web/blob/3ea56250fa9d082e944bebdbf32ddf81d48a7635/ad_manager/util/local_config_generator.py#L450)):*
> ```Python
>         'global': {
>             'scrape_interval': '5s',
>             'evaluation_interval': '15s',
> ```

`5s`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75)*

**Comment by ercanucan** [comment]
Review status: 1 of 3 files reviewed at latest revision, 14 unresolved discussions.

---

*[ad_manager/util/local_config_generator.py, line 59 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-Kh22LRqsTKuUtYrXqWt:-Kh7BqNmCazPwmcYLns8:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/3ea56250fa9d082e944bebdbf32ddf81d48a7635/ad_manager/util/local_config_generator.py#L59)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

These all seem to be only referenced once - in the dict mapping service to executable. In that case, you might as well just put the literals into the dict, and not define them separately.
</blockquote></details>

Done.

---

*[ad_manager/util/local_config_generator.py, line 67 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-Kh2S6oVAY0eRAMVUbPk:-Kh7iI7OY7Lb3S93LUtE:by2quj1) ([raw file](https://github.com/netsec-ethz/scion-web/blob/3ea56250fa9d082e944bebdbf32ddf81d48a7635/ad_manager/util/local_config_generator.py#L67)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This isn't correct (and isn't used, apparently).
</blockquote></details>

Done according to your feedback above.

---

*[ad_manager/util/local_config_generator.py, line 69 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-Kh2KlYUVaiWlZCegDEj:-Kh7Bu-EQluGDbbh50QD:b-wzht19) ([raw file](https://github.com/netsec-ethz/scion-web/blob/3ea56250fa9d082e944bebdbf32ddf81d48a7635/ad_manager/util/local_config_generator.py#L69)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

As scion-web doesn't handle managed zookeeper instances, why is this needed/used?
</blockquote></details>

Frank had this code which we thought we may use in the future for managed zk instances. Removed.

---

*[ad_manager/util/local_config_generator.py, line 85 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-Kh21SOC-8P54F0s9q-T:-Kh7HuPcNfHvgAdgijnh:bh2180k) ([raw file](https://github.com/netsec-ethz/scion-web/blob/3ea56250fa9d082e944bebdbf32ddf81d48a7635/ad_manager/util/local_config_generator.py#L85)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Why a function to return a static dict? It would be more straight-forward to just declare the dicts as module-level constants. (Same for `lookup_dict_executables`).
</blockquote></details>

I believe this is Frank's preferred way. Actually came across another duplicate of this function in `hostfile_generator.py` (which turns out to be the only one needing it). Cleaned it up according to your suggestions.

---

*[ad_manager/util/local_config_generator.py, line 127 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-Kh24KZD-qytaP2LbKLf:-Kh76wdUl2sQBn35PAgr:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/3ea56250fa9d082e944bebdbf32ddf81d48a7635/ad_manager/util/local_config_generator.py#L127)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

As this is a strictly one-to-one mapping, i would just use a single dict. `{"beacon_server": "BeaconServers"....}`
</blockquote></details>

Done.

---

*[ad_manager/util/local_config_generator.py, line 131 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-Kh2Qccnr8O1ZMpx_MUS:-Kh7562pCntzx-Ohyhu1:bghg862) ([raw file](https://github.com/netsec-ethz/scion-web/blob/3ea56250fa9d082e944bebdbf32ddf81d48a7635/ad_manager/util/local_config_generator.py#L131)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

What is a "replica"?
</blockquote></details>

"legacy" code inherited from Frank. It actually means `instances`. Changed accordingly.

---

*[ad_manager/util/local_config_generator.py, line 133 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-Kh2Q4xQ5i1TzELXkTCv:-Kh7k9Kg1XSjMR2GZ51d:bm28x67) ([raw file](https://github.com/netsec-ethz/scion-web/blob/3ea56250fa9d082e944bebdbf32ddf81d48a7635/ad_manager/util/local_config_generator.py#L133)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I don't understand this. The paths and executable names are hard-coded in this file. What is this actually trying to protect against?
</blockquote></details>

This is from @fr4nk-w . I also agree we don't need this as the executable names are hard-coded in this file. Cleaned it up.

---

*[ad_manager/util/local_config_generator.py, line 205 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-Kh2ScrVq6Jaq5iIPai2:-Kh7TgvyrCmySC12elL8:b-n73bmu) ([raw file](https://github.com/netsec-ethz/scion-web/blob/3ea56250fa9d082e944bebdbf32ddf81d48a7635/ad_manager/util/local_config_generator.py#L205)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I could three places in this function alone where `gen/ISD%s/AS%s/%s/` is calculated, and about 8 total in this file :/ How about adding a simple utility function like:
```
def get_elem_dir(isd_as, elem_id):
  return "%s/ISD%s/AS%s/%s" % (GEN_PATH, isd_as[0], isd_as[1], elem_id)
```
</blockquote></details>

Done. I have also included the `path`as a parameter so that we can call it to calculate relative or absolute paths.

---

*[ad_manager/util/local_config_generator.py, line 209 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-Kh2SIdBggUOb_MBcrBA:-Kh7cu9F7G-0spL8MrHK:b99r20) ([raw file](https://github.com/netsec-ethz/scion-web/blob/3ea56250fa9d082e944bebdbf32ddf81d48a7635/ad_manager/util/local_config_generator.py#L209)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

There's no need to use so many quotes. There's also no need to define the template separately, especially when it's re-defined every time.
```
cmd = "bash -c 'exec bin/border -id "%s" -confd "%s" &>logs/%s.OUT'" % (
    instance_name, elem_dir, instance_name)
```
</blockquote></details>

Reduced the use of quotes. I modified the `cmd_tmpl` a bit so that we can fill it in a common way for all types of elements after we come out of the if statement.

---

*[ad_manager/util/local_config_generator.py, line 212 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-Kh2Uswra02wu1Jx549w:-Kh6gor9aBgy39ejWbvW:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/3ea56250fa9d082e944bebdbf32ddf81d48a7635/ad_manager/util/local_config_generator.py#L212)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I think this can be dropped.
</blockquote></details>

Done.

---

*[ad_manager/util/local_config_generator.py, line 216 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-Kh2V--BJ7C9vkWPNzci:-Kh87-6-ptOWlOJb9-LG:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/3ea56250fa9d082e944bebdbf32ddf81d48a7635/ad_manager/util/local_config_generator.py#L216)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.

---

*[ad_manager/util/local_config_generator.py, line 221 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-Kh2V4D6l2oJsCCsZoRe:-Kh6c8eEbIwPJ80gg7xY:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/3ea56250fa9d082e944bebdbf32ddf81d48a7635/ad_manager/util/local_config_generator.py#L221)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

These are in a random order, making it hard to read. I suggest you use a similar order to https://github.com/netsec-ethz/scion/blob/master/topology/generator.py#L798
</blockquote></details>

Done.

---

*[ad_manager/util/local_config_generator.py, line 421 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-Kh2WXY9VhTLREVlCvoO:-Kh6cuQIpkEe-M1u6bG7:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/3ea56250fa9d082e944bebdbf32ddf81d48a7635/ad_manager/util/local_config_generator.py#L421)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`for router in tp['BorderRouters'].values():`
</blockquote></details>

Done.

---

*[ad_manager/util/local_config_generator.py, line 450 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-Kh2XGXcyfL9kVkw70Sq:-Kh6cx4f3b2mPu6gjyPu:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/3ea56250fa9d082e944bebdbf32ddf81d48a7635/ad_manager/util/local_config_generator.py#L450)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`5s`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75)*

**Comment by ercanucan** [comment]
@fr4nk-w you can also have a look at this to see whether the changes to your existing code looks good. @kormat It would be great to get your feedback on this PR when you get a chance. I rebased the PR https://github.com/netsec-ethz/scion-web/pull/74 on top of this refactoring and addressed your comments accordingly. So, it would be good to get this one in first, and then I will update the #74. 

---

Review status: 1 of 3 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-:-KhR5ef7aYKERRELw0ca:b-p4r42z)*

**Comment by ercanucan** [comment]
@fr4nk-w @kormat Just wanted to follow-up on this PR. It would be great to get some feedback on this when you get a chance. I can then rebase and update the #74 on this.

---

Review status: 1 of 3 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-:-KiZ7-K36H7240vfWCrP:b90z9yx)*

**Comment by ercanucan** [comment]
Just wanted to ping you guys on this, as it is slightly blocking some other PRs I'd like to send :-)

---

Review status: 1 of 3 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-:-KiodVtYxY0KNK5rVCFQ:b-rnfzfo)*

**Comment by FR4NK-W** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[ad_manager/util/local_config_generator.py, line 59 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-Kh22LRqsTKuUtYrXqWt:-Kj57S-NxbnrqmLieafe:b6qd5mu) ([raw file](https://github.com/netsec-ethz/scion-web/blob/3ea56250fa9d082e944bebdbf32ddf81d48a7635/ad_manager/util/local_config_generator.py#L59)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The idea was to have the executable names defined in lib.defines.py
Would make it easier to keep them in sync between both /topology/generator.py and local_config_generator.py by having them defined uniquely there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75)*

**Comment by FR4NK-W** [comment]
Other than my comment which can be addressed in a separate PR, it looks good to me.

**Comment by ercanucan** [comment]
@kormat ping

**Comment by kormat** [comment]
Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[ad_manager/util/local_config_generator.py, line 59 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-Kh22LRqsTKuUtYrXqWt:-KjN0Hn-5laMxjkRTfGy:b4p7bf1) ([raw file](https://github.com/netsec-ethz/scion-web/blob/3ea56250fa9d082e944bebdbf32ddf81d48a7635/ad_manager/util/local_config_generator.py#L59)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

The idea was to have the executable names defined in lib.defines.py
Would make it easier to keep them in sync between both /topology/generator.py and local_config_generator.py by having them defined uniquely there.
</blockquote></details>

@fr4nk-w  - that makes sense.

---

*[ad_manager/util/local_config_generator.py, line 84 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-KjN0nHN_jW4FQENfmjU:-KjN0nHN_jW4FQENfmjV:b-rj9lhh) ([raw file](https://github.com/netsec-ethz/scion-web/blob/2d0627106b3d45787c7abbb47d1ec84135ec6a1b/ad_manager/util/local_config_generator.py#L84)):*
> ```Python
>     write_dispatcher_config(local_gen_path)
>     as_path = 'ISD%s/AS%s/' % (ia[0], ia[1])
>     as_path = os.path.join(local_gen_path, as_path)
> ```

`as_path = get_elem_dir(local_gen_path, ia, "")` should work.

---

*[ad_manager/util/local_config_generator.py, line 356 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-KjN4OrEzm6tSwYo24uo:-KjN4OrF3aI6iML0Dkuo:b-d2fyg) ([raw file](https://github.com/netsec-ethz/scion-web/blob/2d0627106b3d45787c7abbb47d1ec84135ec6a1b/ad_manager/util/local_config_generator.py#L356)):*
> ```Python
>     for as_obj in all_ases:
>         targets_path = os.path.join(
>             local_gen_path, "ISD%s" % as_obj.isd_id, "AS%s" % as_obj.as_id,
> ```

Doesn't `as_path` already contain this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75)*

**Comment by ercanucan** [comment]
Review status: 2 of 3 files reviewed at latest revision, 9 unresolved discussions.

---

*[ad_manager/util/local_config_generator.py, line 59 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-Kh22LRqsTKuUtYrXqWt:-KjwGfePPNPVH23U-R3R:bj5wzm5) ([raw file](https://github.com/netsec-ethz/scion-web/blob/3ea56250fa9d082e944bebdbf32ddf81d48a7635/ad_manager/util/local_config_generator.py#L59)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

@fr4nk-w  - that makes sense.
</blockquote></details>

Okay, I will send a separate PR for that, as @fr4nk-w suggested, together with some much needed refactoring and cleanup the hostfile_generator.py. Will create an issue for that.

---

*[ad_manager/util/local_config_generator.py, line 84 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-KjN0nHN_jW4FQENfmjU:-KjwFedBA313Gs5jNMs2:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-web/blob/2d0627106b3d45787c7abbb47d1ec84135ec6a1b/ad_manager/util/local_config_generator.py#L84)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`as_path = get_elem_dir(local_gen_path, ia, "")` should work.
</blockquote></details>

Done.

---

*[ad_manager/util/local_config_generator.py, line 356 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-KjN4OrEzm6tSwYo24uo:-KjwH-rwtGwQyTSdZGl1:b-pka265) ([raw file](https://github.com/netsec-ethz/scion-web/blob/2d0627106b3d45787c7abbb47d1ec84135ec6a1b/ad_manager/util/local_config_generator.py#L356)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Doesn't `as_path` already contain this?
</blockquote></details>

The `as_path` contains the path only for the current AS that the topology configuration is being generated for. In this part of the code, we generate and update the top level Prometheus config file for the top level (`gen`) folder. That's why we are looping through all the ASes known to the scion-web instance. I changed it slightly though, now we use `get_elem_dir` function here as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-:-KkBG9dJDABPJIm27ins:bnfp4nl)*

**Comment by ercanucan** [comment]
@FR4NK-W can you please mark resolve remaining discussion on this? I can then merge it.

**Comment by FR4NK-W** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-web/75#-:-KkCjwRuVyYq20DPYCBL:bnfp4nl)*

**Comment by ercanucan** [comment]
thanks!

**Pull request merged**
